//
// bibseq - A library for analyzing sequence data
// Copyright (C) 2012-2016 Nicholas Hathaway <nicholas.hathaway@umassmed.edu>,
// Jeffrey Bailey <Jeffrey.Bailey@umassmed.edu>
//
// This file is part of bibseq.
//
// bibseq is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// bibseq is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with bibseq.  If not, see <http://www.gnu.org/licenses/>.
//
/*
 * substituteMatrix.cpp
 *
 *  Created on: Apr 11, 2014
 *      Author: nickhathaway
 */

#include "substituteMatrix.hpp"
#include "bibseq/helpers/seqUtil.hpp"
namespace bibseq {

std::array<std::array<double, 127>, 127> substituteMatrix::getRates(const std::vector<char> & alphabet)const{
	std::array<std::array<double, 127>, 127> ret;
	std::array<double, 127> sums;
	for( auto rowPos : iter::range(ret.size())){
		for(auto colPos : iter::range(ret[rowPos].size())){
			ret[rowPos][colPos] = 0;
		}
	}

	for(char refBase : alphabet){
		for(char seqBase : alphabet){
			sums[refBase] += mat_[refBase][seqBase];
		}
	}
	for(char refBase : alphabet){
		for(char seqBase : alphabet){
			ret[refBase][seqBase] = mat_[refBase][seqBase]/sums[refBase];
		}
	}
	return ret;
}

Json::Value substituteMatrix::toJson() const {
	Json::Value ret;
	ret["class"] = "bibseq::substituteMatrix";
	ret["mat_"] = bib::json::toJson(mat_);
	return ret;
}


std::vector<char> substituteMatrix::determineLetters()const{
	std::set<char> retSet;
	for(const auto & row : iter::range(mat_.size())){
		for(const auto & col : iter::range(mat_[row].size())){
			if(mat_[row][col] > 0){
				retSet.emplace(static_cast<char>(row));
				retSet.emplace(static_cast<char>(col));
			}
		}
	}
	std::vector<char> ret(retSet.begin(), retSet.end());
	return ret;
}

void substituteMatrix::setWithZeros(){
	for(const auto & row : iter::range(mat_.size())){
		for(const auto & col : iter::range(mat_[row].size())){
			mat_[row][col] = 0;
		}
	}
}
void substituteMatrix::setWithSimple(int32_t match, int32_t mismatch){
	for(const auto & row : iter::range(mat_.size())){
		for(const auto & col : iter::range(mat_[row].size())){
			if(row == col){
				mat_[row][col] = match;
			}else{
				mat_[row][col] = mismatch;
			}
		}
	}
}

void substituteMatrix::setWithSimpleCaseInsense(int32_t match, int32_t mismatch){
  for (auto i : iter::range(mat_.size())) {
    for (auto j : iter::range(mat_[i].size())) {
      if (i == j) {
      	mat_[i][j] = match;
      } else {
      	mat_[i][j] = mismatch;
      }
    }
  }
  std::vector<char> upperCase(26);
  std::iota(upperCase.begin(), upperCase.end(), 'A');
  std::vector<char> lowerCase(26);
  std::iota(lowerCase.begin(), lowerCase.end(), 'a');
  for (const auto& i : iter::range(lowerCase.size())) {
  	mat_[upperCase[i]][lowerCase[i]] = match;
  	mat_[lowerCase[i]][upperCase[i]] = match;
  }
}

void substituteMatrix::setWithMap(const std::map<char, std::map<char, int32_t>> & mapScores){
	setWithZeros();
	for(const auto & row : mapScores){
		for(const auto & col : row.second){
      if (row.first < 0 || row.first > 126 || col.first < 0 ||
      		col.first > 126) {
      	std::stringstream ss;
        ss << "Unsupported letter supplied for scoring matrix"
                  << std::endl;
        ss << "Only ascii character 0-126 supported " << std::endl;
        ss << "Current letters: " << row.first << " and "
                  << col.first << std::endl;
        throw std::runtime_error{ss.str()};
      }
			mat_[row.first][col.first] = col.second;
		}
	}
}
void substituteMatrix::setWithUnoMap(const std::unordered_map<char, std::unordered_map<char, int32_t>> & mapScores){
	setWithZeros();
	for(const auto & row : mapScores){
		for(const auto & col : row.second){
      if (row.first < 0 || row.first > 126 || col.first < 0 ||
      		col.first > 126) {
      	std::stringstream ss;
        ss << "Unsupported letter supplied for scoring matrix"
                  << std::endl;
        ss << "Only ascii character 0-126 supported " << std::endl;
        ss << "Current letters: " << row.first << " and "
                  << col.first << std::endl;
        throw std::runtime_error{ss.str()};
      }
      //std::cout << row.first << ":" << col.second << "=" <<
			mat_[row.first][col.first] = col.second;
		}
	}
}
void substituteMatrix::setWtihDNAArray(const int matchMatrix[4][4]){
	setWithZeros();
  // update the score array with the scores supplied by the array assuming the
  // order of A,C,G,T
  // A
  mat_['A']['A'] = matchMatrix[0][0];
  mat_['A']['C'] = matchMatrix[0][1];
  mat_['A']['G'] = matchMatrix[0][2];
  mat_['A']['T'] = matchMatrix[0][3];
  // C
  mat_['C']['A'] = matchMatrix[1][0];
  mat_['C']['C'] = matchMatrix[1][1];
  mat_['C']['G'] = matchMatrix[1][2];
  mat_['C']['T'] = matchMatrix[1][3];
  // G
  mat_['G']['A'] = matchMatrix[2][0];
  mat_['G']['C'] = matchMatrix[2][1];
  mat_['G']['G'] = matchMatrix[2][2];
  mat_['G']['T'] = matchMatrix[2][3];
  // T
  mat_['T']['A'] = matchMatrix[3][0];
  mat_['T']['C'] = matchMatrix[3][1];
  mat_['T']['G'] = matchMatrix[3][2];
  mat_['T']['T'] = matchMatrix[3][3];
}

void substituteMatrix::setWtihBlosum62(){
	setWithZeros();
	mat_['Y']['Y'] = 7;
	mat_['Y']['W'] = 2;
	mat_['Y']['V'] = -1;
	mat_['Y']['T'] = -2;
	mat_['Y']['S'] = -2;
	mat_['Y']['R'] = -2;
	mat_['Y']['Q'] = -1;
	mat_['Y']['P'] = -3;
	mat_['Y']['N'] = -2;
	mat_['Y']['M'] = -1;
	mat_['Y']['A'] = -2;
	mat_['Y']['L'] = -1;
	mat_['Y']['C'] = -2;
	mat_['Y']['D'] = -3;
	mat_['Y']['E'] = -2;
	mat_['Y']['F'] = 3;
	mat_['Y']['G'] = -3;
	mat_['Y']['H'] = 2;
	mat_['Y']['I'] = -1;
	mat_['Y']['K'] = -2;
	mat_['W']['Y'] = 2;
	mat_['W']['W'] = 11;
	mat_['W']['V'] = -3;
	mat_['W']['T'] = -2;
	mat_['W']['S'] = -3;
	mat_['W']['R'] = -3;
	mat_['W']['Q'] = -2;
	mat_['W']['P'] = -4;
	mat_['W']['N'] = -4;
	mat_['W']['M'] = -1;
	mat_['W']['A'] = -3;
	mat_['W']['L'] = -2;
	mat_['W']['C'] = -2;
	mat_['W']['D'] = -4;
	mat_['W']['E'] = -3;
	mat_['W']['F'] = 1;
	mat_['W']['G'] = -2;
	mat_['W']['H'] = -2;
	mat_['W']['I'] = -3;
	mat_['W']['K'] = -3;
	mat_['V']['Y'] = -1;
	mat_['V']['W'] = -3;
	mat_['V']['V'] = 4;
	mat_['V']['T'] = 0;
	mat_['V']['S'] = -2;
	mat_['V']['R'] = -3;
	mat_['V']['Q'] = -2;
	mat_['V']['P'] = -2;
	mat_['V']['N'] = -3;
	mat_['V']['M'] = 1;
	mat_['V']['A'] = 0;
	mat_['V']['L'] = 1;
	mat_['V']['C'] = -1;
	mat_['V']['D'] = -3;
	mat_['V']['E'] = -2;
	mat_['V']['F'] = -1;
	mat_['V']['G'] = -3;
	mat_['V']['H'] = -3;
	mat_['V']['I'] = 3;
	mat_['V']['K'] = -2;
	mat_['T']['Y'] = -2;
	mat_['T']['W'] = -2;
	mat_['T']['V'] = 0;
	mat_['T']['T'] = 5;
	mat_['T']['S'] = 1;
	mat_['T']['R'] = -1;
	mat_['T']['Q'] = -1;
	mat_['T']['P'] = -1;
	mat_['T']['N'] = 0;
	mat_['T']['M'] = -1;
	mat_['T']['A'] = 0;
	mat_['T']['L'] = -1;
	mat_['T']['C'] = -1;
	mat_['T']['D'] = -1;
	mat_['T']['E'] = -1;
	mat_['T']['F'] = -2;
	mat_['T']['G'] = -2;
	mat_['T']['H'] = -2;
	mat_['T']['I'] = -1;
	mat_['T']['K'] = -1;
	mat_['S']['Y'] = -2;
	mat_['S']['W'] = -3;
	mat_['S']['V'] = -2;
	mat_['S']['T'] = 1;
	mat_['S']['S'] = 4;
	mat_['S']['R'] = -1;
	mat_['S']['Q'] = 0;
	mat_['S']['P'] = -1;
	mat_['S']['N'] = 1;
	mat_['S']['M'] = -1;
	mat_['S']['A'] = 1;
	mat_['S']['L'] = -2;
	mat_['S']['C'] = -1;
	mat_['S']['D'] = 0;
	mat_['S']['E'] = 0;
	mat_['S']['F'] = -2;
	mat_['S']['G'] = 0;
	mat_['S']['H'] = -1;
	mat_['S']['I'] = -2;
	mat_['S']['K'] = 0;
	mat_['R']['Y'] = -2;
	mat_['R']['W'] = -3;
	mat_['R']['V'] = -3;
	mat_['R']['T'] = -1;
	mat_['R']['S'] = -1;
	mat_['R']['R'] = 5;
	mat_['R']['Q'] = 1;
	mat_['R']['P'] = -2;
	mat_['R']['N'] = 0;
	mat_['R']['M'] = -1;
	mat_['R']['A'] = -1;
	mat_['R']['L'] = -2;
	mat_['R']['C'] = -3;
	mat_['R']['D'] = -2;
	mat_['R']['E'] = 0;
	mat_['R']['F'] = -3;
	mat_['R']['G'] = -2;
	mat_['R']['H'] = 0;
	mat_['R']['I'] = -3;
	mat_['R']['K'] = 2;
	mat_['Q']['Y'] = -1;
	mat_['Q']['W'] = -2;
	mat_['Q']['V'] = -2;
	mat_['Q']['T'] = -1;
	mat_['Q']['S'] = 0;
	mat_['Q']['R'] = 1;
	mat_['Q']['Q'] = 5;
	mat_['Q']['P'] = -1;
	mat_['Q']['N'] = 0;
	mat_['Q']['M'] = 0;
	mat_['Q']['A'] = -1;
	mat_['Q']['L'] = -2;
	mat_['Q']['C'] = -3;
	mat_['Q']['D'] = 0;
	mat_['Q']['E'] = 2;
	mat_['Q']['F'] = -3;
	mat_['Q']['G'] = -2;
	mat_['Q']['H'] = 0;
	mat_['Q']['I'] = -3;
	mat_['Q']['K'] = 1;
	mat_['P']['Y'] = -3;
	mat_['P']['W'] = -4;
	mat_['P']['V'] = -2;
	mat_['P']['T'] = -1;
	mat_['P']['S'] = -1;
	mat_['P']['R'] = -2;
	mat_['P']['Q'] = -1;
	mat_['P']['P'] = 7;
	mat_['P']['N'] = -2;
	mat_['P']['M'] = -2;
	mat_['P']['A'] = -1;
	mat_['P']['L'] = -3;
	mat_['P']['C'] = -3;
	mat_['P']['D'] = -1;
	mat_['P']['E'] = -1;
	mat_['P']['F'] = -4;
	mat_['P']['G'] = -2;
	mat_['P']['H'] = -2;
	mat_['P']['I'] = -3;
	mat_['P']['K'] = -1;
	mat_['N']['Y'] = -2;
	mat_['N']['W'] = -4;
	mat_['N']['V'] = -3;
	mat_['N']['T'] = 0;
	mat_['N']['S'] = 1;
	mat_['N']['R'] = 0;
	mat_['N']['Q'] = 0;
	mat_['N']['P'] = -2;
	mat_['N']['N'] = 6;
	mat_['N']['M'] = -2;
	mat_['N']['A'] = -2;
	mat_['N']['L'] = -3;
	mat_['N']['C'] = -3;
	mat_['N']['D'] = 1;
	mat_['N']['E'] = 0;
	mat_['N']['F'] = -3;
	mat_['N']['G'] = 0;
	mat_['N']['H'] = 1;
	mat_['N']['I'] = -3;
	mat_['N']['K'] = 0;
	mat_['M']['Y'] = -1;
	mat_['M']['W'] = -1;
	mat_['M']['V'] = 1;
	mat_['M']['T'] = -1;
	mat_['M']['S'] = -1;
	mat_['M']['R'] = -1;
	mat_['M']['Q'] = 0;
	mat_['M']['P'] = -2;
	mat_['M']['N'] = -2;
	mat_['M']['M'] = 5;
	mat_['M']['A'] = -1;
	mat_['M']['L'] = 2;
	mat_['M']['C'] = -1;
	mat_['M']['D'] = -3;
	mat_['M']['E'] = -2;
	mat_['M']['F'] = 0;
	mat_['M']['G'] = -3;
	mat_['M']['H'] = -2;
	mat_['M']['I'] = 1;
	mat_['M']['K'] = -1;
	mat_['A']['Y'] = -2;
	mat_['A']['W'] = -3;
	mat_['A']['V'] = 0;
	mat_['A']['T'] = 0;
	mat_['A']['S'] = 1;
	mat_['A']['R'] = -1;
	mat_['A']['Q'] = -1;
	mat_['A']['P'] = -1;
	mat_['A']['N'] = -2;
	mat_['A']['M'] = -1;
	mat_['A']['A'] = 4;
	mat_['A']['L'] = -1;
	mat_['A']['C'] = 0;
	mat_['A']['D'] = -2;
	mat_['A']['E'] = -1;
	mat_['A']['F'] = -2;
	mat_['A']['G'] = 0;
	mat_['A']['H'] = -2;
	mat_['A']['I'] = -1;
	mat_['A']['K'] = -1;
	mat_['L']['Y'] = -1;
	mat_['L']['W'] = -2;
	mat_['L']['V'] = 1;
	mat_['L']['T'] = -1;
	mat_['L']['S'] = -2;
	mat_['L']['R'] = -2;
	mat_['L']['Q'] = -2;
	mat_['L']['P'] = -3;
	mat_['L']['N'] = -3;
	mat_['L']['M'] = 2;
	mat_['L']['A'] = -1;
	mat_['L']['L'] = 4;
	mat_['L']['C'] = -1;
	mat_['L']['D'] = -4;
	mat_['L']['E'] = -3;
	mat_['L']['F'] = 0;
	mat_['L']['G'] = -4;
	mat_['L']['H'] = -3;
	mat_['L']['I'] = 2;
	mat_['L']['K'] = -2;
	mat_['C']['Y'] = -2;
	mat_['C']['W'] = -2;
	mat_['C']['V'] = -1;
	mat_['C']['T'] = -1;
	mat_['C']['S'] = -1;
	mat_['C']['R'] = -3;
	mat_['C']['Q'] = -3;
	mat_['C']['P'] = -3;
	mat_['C']['N'] = -3;
	mat_['C']['M'] = -1;
	mat_['C']['A'] = 0;
	mat_['C']['L'] = -1;
	mat_['C']['C'] = 9;
	mat_['C']['D'] = -3;
	mat_['C']['E'] = -4;
	mat_['C']['F'] = -2;
	mat_['C']['G'] = -3;
	mat_['C']['H'] = -3;
	mat_['C']['I'] = -1;
	mat_['C']['K'] = -3;
	mat_['D']['Y'] = -3;
	mat_['D']['W'] = -4;
	mat_['D']['V'] = -3;
	mat_['D']['T'] = -1;
	mat_['D']['S'] = 0;
	mat_['D']['R'] = -2;
	mat_['D']['Q'] = 0;
	mat_['D']['P'] = -1;
	mat_['D']['N'] = 1;
	mat_['D']['M'] = -3;
	mat_['D']['A'] = -2;
	mat_['D']['L'] = -4;
	mat_['D']['C'] = -3;
	mat_['D']['D'] = 6;
	mat_['D']['E'] = 2;
	mat_['D']['F'] = -3;
	mat_['D']['G'] = -1;
	mat_['D']['H'] = -1;
	mat_['D']['I'] = -3;
	mat_['D']['K'] = -1;
	mat_['E']['Y'] = -2;
	mat_['E']['W'] = -3;
	mat_['E']['V'] = -2;
	mat_['E']['T'] = -1;
	mat_['E']['S'] = 0;
	mat_['E']['R'] = 0;
	mat_['E']['Q'] = 2;
	mat_['E']['P'] = -1;
	mat_['E']['N'] = 0;
	mat_['E']['M'] = -2;
	mat_['E']['A'] = -1;
	mat_['E']['L'] = -3;
	mat_['E']['C'] = -4;
	mat_['E']['D'] = 2;
	mat_['E']['E'] = 5;
	mat_['E']['F'] = -3;
	mat_['E']['G'] = -2;
	mat_['E']['H'] = 0;
	mat_['E']['I'] = -3;
	mat_['E']['K'] = 1;
	mat_['F']['Y'] = 3;
	mat_['F']['W'] = 1;
	mat_['F']['V'] = -1;
	mat_['F']['T'] = -2;
	mat_['F']['S'] = -2;
	mat_['F']['R'] = -3;
	mat_['F']['Q'] = -3;
	mat_['F']['P'] = -4;
	mat_['F']['N'] = -3;
	mat_['F']['M'] = 0;
	mat_['F']['A'] = -2;
	mat_['F']['L'] = 0;
	mat_['F']['C'] = -2;
	mat_['F']['D'] = -3;
	mat_['F']['E'] = -3;
	mat_['F']['F'] = 6;
	mat_['F']['G'] = -3;
	mat_['F']['H'] = -1;
	mat_['F']['I'] = 0;
	mat_['F']['K'] = -3;
	mat_['G']['Y'] = -3;
	mat_['G']['W'] = -2;
	mat_['G']['V'] = -3;
	mat_['G']['T'] = -2;
	mat_['G']['S'] = 0;
	mat_['G']['R'] = -2;
	mat_['G']['Q'] = -2;
	mat_['G']['P'] = -2;
	mat_['G']['N'] = 0;
	mat_['G']['M'] = -3;
	mat_['G']['A'] = 0;
	mat_['G']['L'] = -4;
	mat_['G']['C'] = -3;
	mat_['G']['D'] = -1;
	mat_['G']['E'] = -2;
	mat_['G']['F'] = -3;
	mat_['G']['G'] = 6;
	mat_['G']['H'] = -2;
	mat_['G']['I'] = -4;
	mat_['G']['K'] = -2;
	mat_['H']['Y'] = 2;
	mat_['H']['W'] = -2;
	mat_['H']['V'] = -3;
	mat_['H']['T'] = -2;
	mat_['H']['S'] = -1;
	mat_['H']['R'] = 0;
	mat_['H']['Q'] = 0;
	mat_['H']['P'] = -2;
	mat_['H']['N'] = 1;
	mat_['H']['M'] = -2;
	mat_['H']['A'] = -2;
	mat_['H']['L'] = -3;
	mat_['H']['C'] = -3;
	mat_['H']['D'] = -1;
	mat_['H']['E'] = 0;
	mat_['H']['F'] = -1;
	mat_['H']['G'] = -2;
	mat_['H']['H'] = 8;
	mat_['H']['I'] = -3;
	mat_['H']['K'] = -1;
	mat_['I']['Y'] = -1;
	mat_['I']['W'] = -3;
	mat_['I']['V'] = 3;
	mat_['I']['T'] = -1;
	mat_['I']['S'] = -2;
	mat_['I']['R'] = -3;
	mat_['I']['Q'] = -3;
	mat_['I']['P'] = -3;
	mat_['I']['N'] = -3;
	mat_['I']['M'] = 1;
	mat_['I']['A'] = -1;
	mat_['I']['L'] = 2;
	mat_['I']['C'] = -1;
	mat_['I']['D'] = -3;
	mat_['I']['E'] = -3;
	mat_['I']['F'] = 0;
	mat_['I']['G'] = -4;
	mat_['I']['H'] = -3;
	mat_['I']['I'] = 4;
	mat_['I']['K'] = -3;
	mat_['K']['Y'] = -2;
	mat_['K']['W'] = -3;
	mat_['K']['V'] = -2;
	mat_['K']['T'] = -1;
	mat_['K']['S'] = 0;
	mat_['K']['R'] = 2;
	mat_['K']['Q'] = 1;
	mat_['K']['P'] = -1;
	mat_['K']['N'] = 0;
	mat_['K']['M'] = -1;
	mat_['K']['A'] = -1;
	mat_['K']['L'] = -2;
	mat_['K']['C'] = -3;
	mat_['K']['D'] = -1;
	mat_['K']['E'] = 1;
	mat_['K']['F'] = -3;
	mat_['K']['G'] = -2;
	mat_['K']['H'] = -1;
	mat_['K']['I'] = -3;
	mat_['K']['K'] = 5;
}
void substituteMatrix::setWithPam250(){
	setWithZeros();
	mat_['Y']['Y'] = 10;
	mat_['Y']['W'] = 0;
	mat_['Y']['V'] = -2;
	mat_['Y']['T'] = -3;
	mat_['Y']['S'] = -3;
	mat_['Y']['R'] = -4;
	mat_['Y']['Q'] = -4;
	mat_['Y']['P'] = -5;
	mat_['Y']['N'] = -2;
	mat_['Y']['M'] = -2;
	mat_['Y']['A'] = -3;
	mat_['Y']['L'] = -1;
	mat_['Y']['C'] = 0;
	mat_['Y']['D'] = -4;
	mat_['Y']['E'] = -4;
	mat_['Y']['F'] = 7;
	mat_['Y']['G'] = -5;
	mat_['Y']['H'] = 0;
	mat_['Y']['I'] = -1;
	mat_['Y']['K'] = -4;
	mat_['W']['Y'] = 0;
	mat_['W']['W'] = 17;
	mat_['W']['V'] = -6;
	mat_['W']['T'] = -5;
	mat_['W']['S'] = -2;
	mat_['W']['R'] = 2;
	mat_['W']['Q'] = -5;
	mat_['W']['P'] = -6;
	mat_['W']['N'] = -4;
	mat_['W']['M'] = -4;
	mat_['W']['A'] = -6;
	mat_['W']['L'] = -2;
	mat_['W']['C'] = -8;
	mat_['W']['D'] = -7;
	mat_['W']['E'] = -7;
	mat_['W']['F'] = 0;
	mat_['W']['G'] = -7;
	mat_['W']['H'] = -3;
	mat_['W']['I'] = -5;
	mat_['W']['K'] = -3;
	mat_['V']['Y'] = -2;
	mat_['V']['W'] = -6;
	mat_['V']['V'] = 4;
	mat_['V']['T'] = 0;
	mat_['V']['S'] = -1;
	mat_['V']['R'] = -2;
	mat_['V']['Q'] = -2;
	mat_['V']['P'] = -1;
	mat_['V']['N'] = -2;
	mat_['V']['M'] = 2;
	mat_['V']['A'] = 0;
	mat_['V']['L'] = 2;
	mat_['V']['C'] = -2;
	mat_['V']['D'] = -2;
	mat_['V']['E'] = -2;
	mat_['V']['F'] = -1;
	mat_['V']['G'] = -1;
	mat_['V']['H'] = -2;
	mat_['V']['I'] = 4;
	mat_['V']['K'] = -2;
	mat_['T']['Y'] = -3;
	mat_['T']['W'] = -5;
	mat_['T']['V'] = 0;
	mat_['T']['T'] = 3;
	mat_['T']['S'] = 1;
	mat_['T']['R'] = -1;
	mat_['T']['Q'] = -1;
	mat_['T']['P'] = 0;
	mat_['T']['N'] = 0;
	mat_['T']['M'] = -1;
	mat_['T']['A'] = 1;
	mat_['T']['L'] = -2;
	mat_['T']['C'] = -2;
	mat_['T']['D'] = 0;
	mat_['T']['E'] = 0;
	mat_['T']['F'] = -3;
	mat_['T']['G'] = 0;
	mat_['T']['H'] = -1;
	mat_['T']['I'] = 0;
	mat_['T']['K'] = 0;
	mat_['S']['Y'] = -3;
	mat_['S']['W'] = -2;
	mat_['S']['V'] = -1;
	mat_['S']['T'] = 1;
	mat_['S']['S'] = 2;
	mat_['S']['R'] = 0;
	mat_['S']['Q'] = -1;
	mat_['S']['P'] = 1;
	mat_['S']['N'] = 1;
	mat_['S']['M'] = -2;
	mat_['S']['A'] = 1;
	mat_['S']['L'] = -3;
	mat_['S']['C'] = 0;
	mat_['S']['D'] = 0;
	mat_['S']['E'] = 0;
	mat_['S']['F'] = -3;
	mat_['S']['G'] = 1;
	mat_['S']['H'] = -1;
	mat_['S']['I'] = -1;
	mat_['S']['K'] = 0;
	mat_['R']['Y'] = -4;
	mat_['R']['W'] = 2;
	mat_['R']['V'] = -2;
	mat_['R']['T'] = -1;
	mat_['R']['S'] = 0;
	mat_['R']['R'] = 6;
	mat_['R']['Q'] = 1;
	mat_['R']['P'] = 0;
	mat_['R']['N'] = 0;
	mat_['R']['M'] = 0;
	mat_['R']['A'] = -2;
	mat_['R']['L'] = -3;
	mat_['R']['C'] = -4;
	mat_['R']['D'] = -1;
	mat_['R']['E'] = -1;
	mat_['R']['F'] = -4;
	mat_['R']['G'] = -3;
	mat_['R']['H'] = 2;
	mat_['R']['I'] = -2;
	mat_['R']['K'] = 3;
	mat_['Q']['Y'] = -4;
	mat_['Q']['W'] = -5;
	mat_['Q']['V'] = -2;
	mat_['Q']['T'] = -1;
	mat_['Q']['S'] = -1;
	mat_['Q']['R'] = 1;
	mat_['Q']['Q'] = 4;
	mat_['Q']['P'] = 0;
	mat_['Q']['N'] = 1;
	mat_['Q']['M'] = -1;
	mat_['Q']['A'] = 0;
	mat_['Q']['L'] = -2;
	mat_['Q']['C'] = -5;
	mat_['Q']['D'] = 2;
	mat_['Q']['E'] = 2;
	mat_['Q']['F'] = -5;
	mat_['Q']['G'] = -1;
	mat_['Q']['H'] = 3;
	mat_['Q']['I'] = -2;
	mat_['Q']['K'] = 1;
	mat_['P']['Y'] = -5;
	mat_['P']['W'] = -6;
	mat_['P']['V'] = -1;
	mat_['P']['T'] = 0;
	mat_['P']['S'] = 1;
	mat_['P']['R'] = 0;
	mat_['P']['Q'] = 0;
	mat_['P']['P'] = 6;
	mat_['P']['N'] = 0;
	mat_['P']['M'] = -2;
	mat_['P']['A'] = 1;
	mat_['P']['L'] = -3;
	mat_['P']['C'] = -3;
	mat_['P']['D'] = -1;
	mat_['P']['E'] = -1;
	mat_['P']['F'] = -5;
	mat_['P']['G'] = 0;
	mat_['P']['H'] = 0;
	mat_['P']['I'] = -2;
	mat_['P']['K'] = -1;
	mat_['N']['Y'] = -2;
	mat_['N']['W'] = -4;
	mat_['N']['V'] = -2;
	mat_['N']['T'] = 0;
	mat_['N']['S'] = 1;
	mat_['N']['R'] = 0;
	mat_['N']['Q'] = 1;
	mat_['N']['P'] = 0;
	mat_['N']['N'] = 2;
	mat_['N']['M'] = -2;
	mat_['N']['A'] = 0;
	mat_['N']['L'] = -3;
	mat_['N']['C'] = -4;
	mat_['N']['D'] = 2;
	mat_['N']['E'] = 1;
	mat_['N']['F'] = -3;
	mat_['N']['G'] = 0;
	mat_['N']['H'] = 2;
	mat_['N']['I'] = -2;
	mat_['N']['K'] = 1;
	mat_['M']['Y'] = -2;
	mat_['M']['W'] = -4;
	mat_['M']['V'] = 2;
	mat_['M']['T'] = -1;
	mat_['M']['S'] = -2;
	mat_['M']['R'] = 0;
	mat_['M']['Q'] = -1;
	mat_['M']['P'] = -2;
	mat_['M']['N'] = -2;
	mat_['M']['M'] = 6;
	mat_['M']['A'] = -1;
	mat_['M']['L'] = 4;
	mat_['M']['C'] = -5;
	mat_['M']['D'] = -3;
	mat_['M']['E'] = -2;
	mat_['M']['F'] = 0;
	mat_['M']['G'] = -3;
	mat_['M']['H'] = -2;
	mat_['M']['I'] = 2;
	mat_['M']['K'] = 0;
	mat_['A']['Y'] = -3;
	mat_['A']['W'] = -6;
	mat_['A']['V'] = 0;
	mat_['A']['T'] = 1;
	mat_['A']['S'] = 1;
	mat_['A']['R'] = -2;
	mat_['A']['Q'] = 0;
	mat_['A']['P'] = 1;
	mat_['A']['N'] = 0;
	mat_['A']['M'] = -1;
	mat_['A']['A'] = 2;
	mat_['A']['L'] = -2;
	mat_['A']['C'] = -2;
	mat_['A']['D'] = 0;
	mat_['A']['E'] = 0;
	mat_['A']['F'] = -3;
	mat_['A']['G'] = 1;
	mat_['A']['H'] = -1;
	mat_['A']['I'] = -1;
	mat_['A']['K'] = -1;
	mat_['L']['Y'] = -1;
	mat_['L']['W'] = -2;
	mat_['L']['V'] = 2;
	mat_['L']['T'] = -2;
	mat_['L']['S'] = -3;
	mat_['L']['R'] = -3;
	mat_['L']['Q'] = -2;
	mat_['L']['P'] = -3;
	mat_['L']['N'] = -3;
	mat_['L']['M'] = 4;
	mat_['L']['A'] = -2;
	mat_['L']['L'] = 6;
	mat_['L']['C'] = -6;
	mat_['L']['D'] = -4;
	mat_['L']['E'] = -3;
	mat_['L']['F'] = 2;
	mat_['L']['G'] = -4;
	mat_['L']['H'] = -2;
	mat_['L']['I'] = 2;
	mat_['L']['K'] = -3;
	mat_['C']['Y'] = 0;
	mat_['C']['W'] = -8;
	mat_['C']['V'] = -2;
	mat_['C']['T'] = -2;
	mat_['C']['S'] = 0;
	mat_['C']['R'] = -4;
	mat_['C']['Q'] = -5;
	mat_['C']['P'] = -3;
	mat_['C']['N'] = -4;
	mat_['C']['M'] = -5;
	mat_['C']['A'] = -2;
	mat_['C']['L'] = -6;
	mat_['C']['C'] = 12;
	mat_['C']['D'] = -5;
	mat_['C']['E'] = -5;
	mat_['C']['F'] = -4;
	mat_['C']['G'] = -3;
	mat_['C']['H'] = -3;
	mat_['C']['I'] = -2;
	mat_['C']['K'] = -5;
	mat_['D']['Y'] = -4;
	mat_['D']['W'] = -7;
	mat_['D']['V'] = -2;
	mat_['D']['T'] = 0;
	mat_['D']['S'] = 0;
	mat_['D']['R'] = -1;
	mat_['D']['Q'] = 2;
	mat_['D']['P'] = -1;
	mat_['D']['N'] = 2;
	mat_['D']['M'] = -3;
	mat_['D']['A'] = 0;
	mat_['D']['L'] = -4;
	mat_['D']['C'] = -5;
	mat_['D']['D'] = 4;
	mat_['D']['E'] = 3;
	mat_['D']['F'] = -6;
	mat_['D']['G'] = 1;
	mat_['D']['H'] = 1;
	mat_['D']['I'] = -2;
	mat_['D']['K'] = 0;
	mat_['E']['Y'] = -4;
	mat_['E']['W'] = -7;
	mat_['E']['V'] = -2;
	mat_['E']['T'] = 0;
	mat_['E']['S'] = 0;
	mat_['E']['R'] = -1;
	mat_['E']['Q'] = 2;
	mat_['E']['P'] = -1;
	mat_['E']['N'] = 1;
	mat_['E']['M'] = -2;
	mat_['E']['A'] = 0;
	mat_['E']['L'] = -3;
	mat_['E']['C'] = -5;
	mat_['E']['D'] = 3;
	mat_['E']['E'] = 4;
	mat_['E']['F'] = -5;
	mat_['E']['G'] = 0;
	mat_['E']['H'] = 1;
	mat_['E']['I'] = -2;
	mat_['E']['K'] = 0;
	mat_['F']['Y'] = 7;
	mat_['F']['W'] = 0;
	mat_['F']['V'] = -1;
	mat_['F']['T'] = -3;
	mat_['F']['S'] = -3;
	mat_['F']['R'] = -4;
	mat_['F']['Q'] = -5;
	mat_['F']['P'] = -5;
	mat_['F']['N'] = -3;
	mat_['F']['M'] = 0;
	mat_['F']['A'] = -3;
	mat_['F']['L'] = 2;
	mat_['F']['C'] = -4;
	mat_['F']['D'] = -6;
	mat_['F']['E'] = -5;
	mat_['F']['F'] = 9;
	mat_['F']['G'] = -5;
	mat_['F']['H'] = -2;
	mat_['F']['I'] = 1;
	mat_['F']['K'] = -5;
	mat_['G']['Y'] = -5;
	mat_['G']['W'] = -7;
	mat_['G']['V'] = -1;
	mat_['G']['T'] = 0;
	mat_['G']['S'] = 1;
	mat_['G']['R'] = -3;
	mat_['G']['Q'] = -1;
	mat_['G']['P'] = 0;
	mat_['G']['N'] = 0;
	mat_['G']['M'] = -3;
	mat_['G']['A'] = 1;
	mat_['G']['L'] = -4;
	mat_['G']['C'] = -3;
	mat_['G']['D'] = 1;
	mat_['G']['E'] = 0;
	mat_['G']['F'] = -5;
	mat_['G']['G'] = 5;
	mat_['G']['H'] = -2;
	mat_['G']['I'] = -3;
	mat_['G']['K'] = -2;
	mat_['H']['Y'] = 0;
	mat_['H']['W'] = -3;
	mat_['H']['V'] = -2;
	mat_['H']['T'] = -1;
	mat_['H']['S'] = -1;
	mat_['H']['R'] = 2;
	mat_['H']['Q'] = 3;
	mat_['H']['P'] = 0;
	mat_['H']['N'] = 2;
	mat_['H']['M'] = -2;
	mat_['H']['A'] = -1;
	mat_['H']['L'] = -2;
	mat_['H']['C'] = -3;
	mat_['H']['D'] = 1;
	mat_['H']['E'] = 1;
	mat_['H']['F'] = -2;
	mat_['H']['G'] = -2;
	mat_['H']['H'] = 6;
	mat_['H']['I'] = -2;
	mat_['H']['K'] = 0;
	mat_['I']['Y'] = -1;
	mat_['I']['W'] = -5;
	mat_['I']['V'] = 4;
	mat_['I']['T'] = 0;
	mat_['I']['S'] = -1;
	mat_['I']['R'] = -2;
	mat_['I']['Q'] = -2;
	mat_['I']['P'] = -2;
	mat_['I']['N'] = -2;
	mat_['I']['M'] = 2;
	mat_['I']['A'] = -1;
	mat_['I']['L'] = 2;
	mat_['I']['C'] = -2;
	mat_['I']['D'] = -2;
	mat_['I']['E'] = -2;
	mat_['I']['F'] = 1;
	mat_['I']['G'] = -3;
	mat_['I']['H'] = -2;
	mat_['I']['I'] = 5;
	mat_['I']['K'] = -2;
	mat_['K']['Y'] = -4;
	mat_['K']['W'] = -3;
	mat_['K']['V'] = -2;
	mat_['K']['T'] = 0;
	mat_['K']['S'] = 0;
	mat_['K']['R'] = 3;
	mat_['K']['Q'] = 1;
	mat_['K']['P'] = -1;
	mat_['K']['N'] = 1;
	mat_['K']['M'] = 0;
	mat_['K']['A'] = -1;
	mat_['K']['L'] = -3;
	mat_['K']['C'] = -5;
	mat_['K']['D'] = 0;
	mat_['K']['E'] = 0;
	mat_['K']['F'] = -5;
	mat_['K']['G'] = -2;
	mat_['K']['H'] = 0;
	mat_['K']['I'] = -2;
	mat_['K']['K'] = 5;
}

void substituteMatrix::setWithDegenScoringCaseInsen(int32_t matchScore, int32_t mismatchScore){
	setWithSimpleCaseInsense(matchScore, mismatchScore);
	mat_['A']['D'] = matchScore;
	mat_['D']['A'] = matchScore;
	mat_['a']['D'] = matchScore;
	mat_['D']['a'] = matchScore;
	mat_['A']['d'] = matchScore;
	mat_['d']['A'] = matchScore;
	mat_['a']['d'] = matchScore;
	mat_['d']['a'] = matchScore;
	mat_['A']['V'] = matchScore;
	mat_['V']['A'] = matchScore;
	mat_['a']['V'] = matchScore;
	mat_['V']['a'] = matchScore;
	mat_['A']['v'] = matchScore;
	mat_['v']['A'] = matchScore;
	mat_['a']['v'] = matchScore;
	mat_['v']['a'] = matchScore;
	mat_['A']['N'] = matchScore;
	mat_['N']['A'] = matchScore;
	mat_['a']['N'] = matchScore;
	mat_['N']['a'] = matchScore;
	mat_['A']['n'] = matchScore;
	mat_['n']['A'] = matchScore;
	mat_['a']['n'] = matchScore;
	mat_['n']['a'] = matchScore;
	mat_['A']['H'] = matchScore;
	mat_['H']['A'] = matchScore;
	mat_['a']['H'] = matchScore;
	mat_['H']['a'] = matchScore;
	mat_['A']['h'] = matchScore;
	mat_['h']['A'] = matchScore;
	mat_['a']['h'] = matchScore;
	mat_['h']['a'] = matchScore;
	mat_['A']['W'] = matchScore;
	mat_['W']['A'] = matchScore;
	mat_['a']['W'] = matchScore;
	mat_['W']['a'] = matchScore;
	mat_['A']['w'] = matchScore;
	mat_['w']['A'] = matchScore;
	mat_['a']['w'] = matchScore;
	mat_['w']['a'] = matchScore;
	mat_['A']['R'] = matchScore;
	mat_['R']['A'] = matchScore;
	mat_['a']['R'] = matchScore;
	mat_['R']['a'] = matchScore;
	mat_['A']['r'] = matchScore;
	mat_['r']['A'] = matchScore;
	mat_['a']['r'] = matchScore;
	mat_['r']['a'] = matchScore;
	mat_['A']['M'] = matchScore;
	mat_['M']['A'] = matchScore;
	mat_['a']['M'] = matchScore;
	mat_['M']['a'] = matchScore;
	mat_['A']['m'] = matchScore;
	mat_['m']['A'] = matchScore;
	mat_['a']['m'] = matchScore;
	mat_['m']['a'] = matchScore;
	mat_['C']['V'] = matchScore;
	mat_['V']['C'] = matchScore;
	mat_['c']['V'] = matchScore;
	mat_['V']['c'] = matchScore;
	mat_['C']['v'] = matchScore;
	mat_['v']['C'] = matchScore;
	mat_['c']['v'] = matchScore;
	mat_['v']['c'] = matchScore;
	mat_['C']['N'] = matchScore;
	mat_['N']['C'] = matchScore;
	mat_['c']['N'] = matchScore;
	mat_['N']['c'] = matchScore;
	mat_['C']['n'] = matchScore;
	mat_['n']['C'] = matchScore;
	mat_['c']['n'] = matchScore;
	mat_['n']['c'] = matchScore;
	mat_['C']['Y'] = matchScore;
	mat_['Y']['C'] = matchScore;
	mat_['c']['Y'] = matchScore;
	mat_['Y']['c'] = matchScore;
	mat_['C']['y'] = matchScore;
	mat_['y']['C'] = matchScore;
	mat_['c']['y'] = matchScore;
	mat_['y']['c'] = matchScore;
	mat_['C']['H'] = matchScore;
	mat_['H']['C'] = matchScore;
	mat_['c']['H'] = matchScore;
	mat_['H']['c'] = matchScore;
	mat_['C']['h'] = matchScore;
	mat_['h']['C'] = matchScore;
	mat_['c']['h'] = matchScore;
	mat_['h']['c'] = matchScore;
	mat_['C']['S'] = matchScore;
	mat_['S']['C'] = matchScore;
	mat_['c']['S'] = matchScore;
	mat_['S']['c'] = matchScore;
	mat_['C']['s'] = matchScore;
	mat_['s']['C'] = matchScore;
	mat_['c']['s'] = matchScore;
	mat_['s']['c'] = matchScore;
	mat_['C']['B'] = matchScore;
	mat_['B']['C'] = matchScore;
	mat_['c']['B'] = matchScore;
	mat_['B']['c'] = matchScore;
	mat_['C']['b'] = matchScore;
	mat_['b']['C'] = matchScore;
	mat_['c']['b'] = matchScore;
	mat_['b']['c'] = matchScore;
	mat_['C']['M'] = matchScore;
	mat_['M']['C'] = matchScore;
	mat_['c']['M'] = matchScore;
	mat_['M']['c'] = matchScore;
	mat_['C']['m'] = matchScore;
	mat_['m']['C'] = matchScore;
	mat_['c']['m'] = matchScore;
	mat_['m']['c'] = matchScore;
	mat_['G']['D'] = matchScore;
	mat_['D']['G'] = matchScore;
	mat_['g']['D'] = matchScore;
	mat_['D']['g'] = matchScore;
	mat_['G']['d'] = matchScore;
	mat_['d']['G'] = matchScore;
	mat_['g']['d'] = matchScore;
	mat_['d']['g'] = matchScore;
	mat_['G']['V'] = matchScore;
	mat_['V']['G'] = matchScore;
	mat_['g']['V'] = matchScore;
	mat_['V']['g'] = matchScore;
	mat_['G']['v'] = matchScore;
	mat_['v']['G'] = matchScore;
	mat_['g']['v'] = matchScore;
	mat_['v']['g'] = matchScore;
	mat_['G']['K'] = matchScore;
	mat_['K']['G'] = matchScore;
	mat_['g']['K'] = matchScore;
	mat_['K']['g'] = matchScore;
	mat_['G']['k'] = matchScore;
	mat_['k']['G'] = matchScore;
	mat_['g']['k'] = matchScore;
	mat_['k']['g'] = matchScore;
	mat_['G']['N'] = matchScore;
	mat_['N']['G'] = matchScore;
	mat_['g']['N'] = matchScore;
	mat_['N']['g'] = matchScore;
	mat_['G']['n'] = matchScore;
	mat_['n']['G'] = matchScore;
	mat_['g']['n'] = matchScore;
	mat_['n']['g'] = matchScore;
	mat_['G']['S'] = matchScore;
	mat_['S']['G'] = matchScore;
	mat_['g']['S'] = matchScore;
	mat_['S']['g'] = matchScore;
	mat_['G']['s'] = matchScore;
	mat_['s']['G'] = matchScore;
	mat_['g']['s'] = matchScore;
	mat_['s']['g'] = matchScore;
	mat_['G']['R'] = matchScore;
	mat_['R']['G'] = matchScore;
	mat_['g']['R'] = matchScore;
	mat_['R']['g'] = matchScore;
	mat_['G']['r'] = matchScore;
	mat_['r']['G'] = matchScore;
	mat_['g']['r'] = matchScore;
	mat_['r']['g'] = matchScore;
	mat_['G']['B'] = matchScore;
	mat_['B']['G'] = matchScore;
	mat_['g']['B'] = matchScore;
	mat_['B']['g'] = matchScore;
	mat_['G']['b'] = matchScore;
	mat_['b']['G'] = matchScore;
	mat_['g']['b'] = matchScore;
	mat_['b']['g'] = matchScore;
	mat_['T']['D'] = matchScore;
	mat_['D']['T'] = matchScore;
	mat_['t']['D'] = matchScore;
	mat_['D']['t'] = matchScore;
	mat_['T']['d'] = matchScore;
	mat_['d']['T'] = matchScore;
	mat_['t']['d'] = matchScore;
	mat_['d']['t'] = matchScore;
	mat_['T']['K'] = matchScore;
	mat_['K']['T'] = matchScore;
	mat_['t']['K'] = matchScore;
	mat_['K']['t'] = matchScore;
	mat_['T']['k'] = matchScore;
	mat_['k']['T'] = matchScore;
	mat_['t']['k'] = matchScore;
	mat_['k']['t'] = matchScore;
	mat_['T']['N'] = matchScore;
	mat_['N']['T'] = matchScore;
	mat_['t']['N'] = matchScore;
	mat_['N']['t'] = matchScore;
	mat_['T']['n'] = matchScore;
	mat_['n']['T'] = matchScore;
	mat_['t']['n'] = matchScore;
	mat_['n']['t'] = matchScore;
	mat_['T']['Y'] = matchScore;
	mat_['Y']['T'] = matchScore;
	mat_['t']['Y'] = matchScore;
	mat_['Y']['t'] = matchScore;
	mat_['T']['y'] = matchScore;
	mat_['y']['T'] = matchScore;
	mat_['t']['y'] = matchScore;
	mat_['y']['t'] = matchScore;
	mat_['T']['H'] = matchScore;
	mat_['H']['T'] = matchScore;
	mat_['t']['H'] = matchScore;
	mat_['H']['t'] = matchScore;
	mat_['T']['h'] = matchScore;
	mat_['h']['T'] = matchScore;
	mat_['t']['h'] = matchScore;
	mat_['h']['t'] = matchScore;
	mat_['T']['W'] = matchScore;
	mat_['W']['T'] = matchScore;
	mat_['t']['W'] = matchScore;
	mat_['W']['t'] = matchScore;
	mat_['T']['w'] = matchScore;
	mat_['w']['T'] = matchScore;
	mat_['t']['w'] = matchScore;
	mat_['w']['t'] = matchScore;
	mat_['T']['B'] = matchScore;
	mat_['B']['T'] = matchScore;
	mat_['t']['B'] = matchScore;
	mat_['B']['t'] = matchScore;
	mat_['T']['b'] = matchScore;
	mat_['b']['T'] = matchScore;
	mat_['t']['b'] = matchScore;
	mat_['b']['t'] = matchScore;
	mat_['N']['D'] = matchScore;
	mat_['D']['N'] = matchScore;
	mat_['n']['D'] = matchScore;
	mat_['D']['n'] = matchScore;
	mat_['N']['d'] = matchScore;
	mat_['d']['N'] = matchScore;
	mat_['n']['d'] = matchScore;
	mat_['d']['n'] = matchScore;
	mat_['N']['V'] = matchScore;
	mat_['V']['N'] = matchScore;
	mat_['n']['V'] = matchScore;
	mat_['V']['n'] = matchScore;
	mat_['N']['v'] = matchScore;
	mat_['v']['N'] = matchScore;
	mat_['n']['v'] = matchScore;
	mat_['v']['n'] = matchScore;
	mat_['N']['K'] = matchScore;
	mat_['K']['N'] = matchScore;
	mat_['n']['K'] = matchScore;
	mat_['K']['n'] = matchScore;
	mat_['N']['k'] = matchScore;
	mat_['k']['N'] = matchScore;
	mat_['n']['k'] = matchScore;
	mat_['k']['n'] = matchScore;
	mat_['N']['Y'] = matchScore;
	mat_['Y']['N'] = matchScore;
	mat_['n']['Y'] = matchScore;
	mat_['Y']['n'] = matchScore;
	mat_['N']['y'] = matchScore;
	mat_['y']['N'] = matchScore;
	mat_['n']['y'] = matchScore;
	mat_['y']['n'] = matchScore;
	mat_['N']['H'] = matchScore;
	mat_['H']['N'] = matchScore;
	mat_['n']['H'] = matchScore;
	mat_['H']['n'] = matchScore;
	mat_['N']['h'] = matchScore;
	mat_['h']['N'] = matchScore;
	mat_['n']['h'] = matchScore;
	mat_['h']['n'] = matchScore;
	mat_['N']['S'] = matchScore;
	mat_['S']['N'] = matchScore;
	mat_['n']['S'] = matchScore;
	mat_['S']['n'] = matchScore;
	mat_['N']['s'] = matchScore;
	mat_['s']['N'] = matchScore;
	mat_['n']['s'] = matchScore;
	mat_['s']['n'] = matchScore;
	mat_['N']['W'] = matchScore;
	mat_['W']['N'] = matchScore;
	mat_['n']['W'] = matchScore;
	mat_['W']['n'] = matchScore;
	mat_['N']['w'] = matchScore;
	mat_['w']['N'] = matchScore;
	mat_['n']['w'] = matchScore;
	mat_['w']['n'] = matchScore;
	mat_['N']['R'] = matchScore;
	mat_['R']['N'] = matchScore;
	mat_['n']['R'] = matchScore;
	mat_['R']['n'] = matchScore;
	mat_['N']['r'] = matchScore;
	mat_['r']['N'] = matchScore;
	mat_['n']['r'] = matchScore;
	mat_['r']['n'] = matchScore;
	mat_['N']['B'] = matchScore;
	mat_['B']['N'] = matchScore;
	mat_['n']['B'] = matchScore;
	mat_['B']['n'] = matchScore;
	mat_['N']['b'] = matchScore;
	mat_['b']['N'] = matchScore;
	mat_['n']['b'] = matchScore;
	mat_['b']['n'] = matchScore;
	mat_['N']['M'] = matchScore;
	mat_['M']['N'] = matchScore;
	mat_['n']['M'] = matchScore;
	mat_['M']['n'] = matchScore;
	mat_['N']['m'] = matchScore;
	mat_['m']['N'] = matchScore;
	mat_['n']['m'] = matchScore;
	mat_['m']['n'] = matchScore;
}
void substituteMatrix::setWithDegenScoringLessNCaseInsen(int32_t matchScore, int32_t mismatchScore){
	setWithSimpleCaseInsense(matchScore, mismatchScore);
	mat_['A']['D'] = matchScore - 1;
	mat_['D']['A'] = matchScore - 1;
	mat_['a']['D'] = matchScore - 1;
	mat_['D']['a'] = matchScore - 1;
	mat_['A']['d'] = matchScore - 1;
	mat_['d']['A'] = matchScore - 1;
	mat_['a']['d'] = matchScore - 1;
	mat_['d']['a'] = matchScore - 1;
	mat_['A']['V'] = matchScore - 1;
	mat_['V']['A'] = matchScore - 1;
	mat_['a']['V'] = matchScore - 1;
	mat_['V']['a'] = matchScore - 1;
	mat_['A']['v'] = matchScore - 1;
	mat_['v']['A'] = matchScore - 1;
	mat_['a']['v'] = matchScore - 1;
	mat_['v']['a'] = matchScore - 1;
	mat_['A']['N'] = matchScore - 1;
	mat_['N']['A'] = matchScore - 1;
	mat_['a']['N'] = matchScore - 1;
	mat_['N']['a'] = matchScore - 1;
	mat_['A']['n'] = matchScore - 1;
	mat_['n']['A'] = matchScore - 1;
	mat_['a']['n'] = matchScore - 1;
	mat_['n']['a'] = matchScore - 1;
	mat_['A']['H'] = matchScore - 1;
	mat_['H']['A'] = matchScore - 1;
	mat_['a']['H'] = matchScore - 1;
	mat_['H']['a'] = matchScore - 1;
	mat_['A']['h'] = matchScore - 1;
	mat_['h']['A'] = matchScore - 1;
	mat_['a']['h'] = matchScore - 1;
	mat_['h']['a'] = matchScore - 1;
	mat_['A']['W'] = matchScore - 1;
	mat_['W']['A'] = matchScore - 1;
	mat_['a']['W'] = matchScore - 1;
	mat_['W']['a'] = matchScore - 1;
	mat_['A']['w'] = matchScore - 1;
	mat_['w']['A'] = matchScore - 1;
	mat_['a']['w'] = matchScore - 1;
	mat_['w']['a'] = matchScore - 1;
	mat_['A']['R'] = matchScore - 1;
	mat_['R']['A'] = matchScore - 1;
	mat_['a']['R'] = matchScore - 1;
	mat_['R']['a'] = matchScore - 1;
	mat_['A']['r'] = matchScore - 1;
	mat_['r']['A'] = matchScore - 1;
	mat_['a']['r'] = matchScore - 1;
	mat_['r']['a'] = matchScore - 1;
	mat_['A']['M'] = matchScore - 1;
	mat_['M']['A'] = matchScore - 1;
	mat_['a']['M'] = matchScore - 1;
	mat_['M']['a'] = matchScore - 1;
	mat_['A']['m'] = matchScore - 1;
	mat_['m']['A'] = matchScore - 1;
	mat_['a']['m'] = matchScore - 1;
	mat_['m']['a'] = matchScore - 1;
	mat_['C']['V'] = matchScore - 1;
	mat_['V']['C'] = matchScore - 1;
	mat_['c']['V'] = matchScore - 1;
	mat_['V']['c'] = matchScore - 1;
	mat_['C']['v'] = matchScore - 1;
	mat_['v']['C'] = matchScore - 1;
	mat_['c']['v'] = matchScore - 1;
	mat_['v']['c'] = matchScore - 1;
	mat_['C']['N'] = matchScore - 1;
	mat_['N']['C'] = matchScore - 1;
	mat_['c']['N'] = matchScore - 1;
	mat_['N']['c'] = matchScore - 1;
	mat_['C']['n'] = matchScore - 1;
	mat_['n']['C'] = matchScore - 1;
	mat_['c']['n'] = matchScore - 1;
	mat_['n']['c'] = matchScore - 1;
	mat_['C']['Y'] = matchScore - 1;
	mat_['Y']['C'] = matchScore - 1;
	mat_['c']['Y'] = matchScore - 1;
	mat_['Y']['c'] = matchScore - 1;
	mat_['C']['y'] = matchScore - 1;
	mat_['y']['C'] = matchScore - 1;
	mat_['c']['y'] = matchScore - 1;
	mat_['y']['c'] = matchScore - 1;
	mat_['C']['H'] = matchScore - 1;
	mat_['H']['C'] = matchScore - 1;
	mat_['c']['H'] = matchScore - 1;
	mat_['H']['c'] = matchScore - 1;
	mat_['C']['h'] = matchScore - 1;
	mat_['h']['C'] = matchScore - 1;
	mat_['c']['h'] = matchScore - 1;
	mat_['h']['c'] = matchScore - 1;
	mat_['C']['S'] = matchScore - 1;
	mat_['S']['C'] = matchScore - 1;
	mat_['c']['S'] = matchScore - 1;
	mat_['S']['c'] = matchScore - 1;
	mat_['C']['s'] = matchScore - 1;
	mat_['s']['C'] = matchScore - 1;
	mat_['c']['s'] = matchScore - 1;
	mat_['s']['c'] = matchScore - 1;
	mat_['C']['B'] = matchScore - 1;
	mat_['B']['C'] = matchScore - 1;
	mat_['c']['B'] = matchScore - 1;
	mat_['B']['c'] = matchScore - 1;
	mat_['C']['b'] = matchScore - 1;
	mat_['b']['C'] = matchScore - 1;
	mat_['c']['b'] = matchScore - 1;
	mat_['b']['c'] = matchScore - 1;
	mat_['C']['M'] = matchScore - 1;
	mat_['M']['C'] = matchScore - 1;
	mat_['c']['M'] = matchScore - 1;
	mat_['M']['c'] = matchScore - 1;
	mat_['C']['m'] = matchScore - 1;
	mat_['m']['C'] = matchScore - 1;
	mat_['c']['m'] = matchScore - 1;
	mat_['m']['c'] = matchScore - 1;
	mat_['G']['D'] = matchScore - 1;
	mat_['D']['G'] = matchScore - 1;
	mat_['g']['D'] = matchScore - 1;
	mat_['D']['g'] = matchScore - 1;
	mat_['G']['d'] = matchScore - 1;
	mat_['d']['G'] = matchScore - 1;
	mat_['g']['d'] = matchScore - 1;
	mat_['d']['g'] = matchScore - 1;
	mat_['G']['V'] = matchScore - 1;
	mat_['V']['G'] = matchScore - 1;
	mat_['g']['V'] = matchScore - 1;
	mat_['V']['g'] = matchScore - 1;
	mat_['G']['v'] = matchScore - 1;
	mat_['v']['G'] = matchScore - 1;
	mat_['g']['v'] = matchScore - 1;
	mat_['v']['g'] = matchScore - 1;
	mat_['G']['K'] = matchScore - 1;
	mat_['K']['G'] = matchScore - 1;
	mat_['g']['K'] = matchScore - 1;
	mat_['K']['g'] = matchScore - 1;
	mat_['G']['k'] = matchScore - 1;
	mat_['k']['G'] = matchScore - 1;
	mat_['g']['k'] = matchScore - 1;
	mat_['k']['g'] = matchScore - 1;
	mat_['G']['N'] = matchScore - 1;
	mat_['N']['G'] = matchScore - 1;
	mat_['g']['N'] = matchScore - 1;
	mat_['N']['g'] = matchScore - 1;
	mat_['G']['n'] = matchScore - 1;
	mat_['n']['G'] = matchScore - 1;
	mat_['g']['n'] = matchScore - 1;
	mat_['n']['g'] = matchScore - 1;
	mat_['G']['S'] = matchScore - 1;
	mat_['S']['G'] = matchScore - 1;
	mat_['g']['S'] = matchScore - 1;
	mat_['S']['g'] = matchScore - 1;
	mat_['G']['s'] = matchScore - 1;
	mat_['s']['G'] = matchScore - 1;
	mat_['g']['s'] = matchScore - 1;
	mat_['s']['g'] = matchScore - 1;
	mat_['G']['R'] = matchScore - 1;
	mat_['R']['G'] = matchScore - 1;
	mat_['g']['R'] = matchScore - 1;
	mat_['R']['g'] = matchScore - 1;
	mat_['G']['r'] = matchScore - 1;
	mat_['r']['G'] = matchScore - 1;
	mat_['g']['r'] = matchScore - 1;
	mat_['r']['g'] = matchScore - 1;
	mat_['G']['B'] = matchScore - 1;
	mat_['B']['G'] = matchScore - 1;
	mat_['g']['B'] = matchScore - 1;
	mat_['B']['g'] = matchScore - 1;
	mat_['G']['b'] = matchScore - 1;
	mat_['b']['G'] = matchScore - 1;
	mat_['g']['b'] = matchScore - 1;
	mat_['b']['g'] = matchScore - 1;
	mat_['T']['D'] = matchScore - 1;
	mat_['D']['T'] = matchScore - 1;
	mat_['t']['D'] = matchScore - 1;
	mat_['D']['t'] = matchScore - 1;
	mat_['T']['d'] = matchScore - 1;
	mat_['d']['T'] = matchScore - 1;
	mat_['t']['d'] = matchScore - 1;
	mat_['d']['t'] = matchScore - 1;
	mat_['T']['K'] = matchScore - 1;
	mat_['K']['T'] = matchScore - 1;
	mat_['t']['K'] = matchScore - 1;
	mat_['K']['t'] = matchScore - 1;
	mat_['T']['k'] = matchScore - 1;
	mat_['k']['T'] = matchScore - 1;
	mat_['t']['k'] = matchScore - 1;
	mat_['k']['t'] = matchScore - 1;
	mat_['T']['N'] = matchScore - 1;
	mat_['N']['T'] = matchScore - 1;
	mat_['t']['N'] = matchScore - 1;
	mat_['N']['t'] = matchScore - 1;
	mat_['T']['n'] = matchScore - 1;
	mat_['n']['T'] = matchScore - 1;
	mat_['t']['n'] = matchScore - 1;
	mat_['n']['t'] = matchScore - 1;
	mat_['T']['Y'] = matchScore - 1;
	mat_['Y']['T'] = matchScore - 1;
	mat_['t']['Y'] = matchScore - 1;
	mat_['Y']['t'] = matchScore - 1;
	mat_['T']['y'] = matchScore - 1;
	mat_['y']['T'] = matchScore - 1;
	mat_['t']['y'] = matchScore - 1;
	mat_['y']['t'] = matchScore - 1;
	mat_['T']['H'] = matchScore - 1;
	mat_['H']['T'] = matchScore - 1;
	mat_['t']['H'] = matchScore - 1;
	mat_['H']['t'] = matchScore - 1;
	mat_['T']['h'] = matchScore - 1;
	mat_['h']['T'] = matchScore - 1;
	mat_['t']['h'] = matchScore - 1;
	mat_['h']['t'] = matchScore - 1;
	mat_['T']['W'] = matchScore - 1;
	mat_['W']['T'] = matchScore - 1;
	mat_['t']['W'] = matchScore - 1;
	mat_['W']['t'] = matchScore - 1;
	mat_['T']['w'] = matchScore - 1;
	mat_['w']['T'] = matchScore - 1;
	mat_['t']['w'] = matchScore - 1;
	mat_['w']['t'] = matchScore - 1;
	mat_['T']['B'] = matchScore - 1;
	mat_['B']['T'] = matchScore - 1;
	mat_['t']['B'] = matchScore - 1;
	mat_['B']['t'] = matchScore - 1;
	mat_['T']['b'] = matchScore - 1;
	mat_['b']['T'] = matchScore - 1;
	mat_['t']['b'] = matchScore - 1;
	mat_['b']['t'] = matchScore - 1;
	mat_['N']['D'] = matchScore - 1;
	mat_['D']['N'] = matchScore - 1;
	mat_['n']['D'] = matchScore - 1;
	mat_['D']['n'] = matchScore - 1;
	mat_['N']['d'] = matchScore - 1;
	mat_['d']['N'] = matchScore - 1;
	mat_['n']['d'] = matchScore - 1;
	mat_['d']['n'] = matchScore - 1;
	mat_['N']['V'] = matchScore - 1;
	mat_['V']['N'] = matchScore - 1;
	mat_['n']['V'] = matchScore - 1;
	mat_['V']['n'] = matchScore - 1;
	mat_['N']['v'] = matchScore - 1;
	mat_['v']['N'] = matchScore - 1;
	mat_['n']['v'] = matchScore - 1;
	mat_['v']['n'] = matchScore - 1;
	mat_['N']['K'] = matchScore - 1;
	mat_['K']['N'] = matchScore - 1;
	mat_['n']['K'] = matchScore - 1;
	mat_['K']['n'] = matchScore - 1;
	mat_['N']['k'] = matchScore - 1;
	mat_['k']['N'] = matchScore - 1;
	mat_['n']['k'] = matchScore - 1;
	mat_['k']['n'] = matchScore - 1;
	mat_['N']['Y'] = matchScore - 1;
	mat_['Y']['N'] = matchScore - 1;
	mat_['n']['Y'] = matchScore - 1;
	mat_['Y']['n'] = matchScore - 1;
	mat_['N']['y'] = matchScore - 1;
	mat_['y']['N'] = matchScore - 1;
	mat_['n']['y'] = matchScore - 1;
	mat_['y']['n'] = matchScore - 1;
	mat_['N']['H'] = matchScore - 1;
	mat_['H']['N'] = matchScore - 1;
	mat_['n']['H'] = matchScore - 1;
	mat_['H']['n'] = matchScore - 1;
	mat_['N']['h'] = matchScore - 1;
	mat_['h']['N'] = matchScore - 1;
	mat_['n']['h'] = matchScore - 1;
	mat_['h']['n'] = matchScore - 1;
	mat_['N']['S'] = matchScore - 1;
	mat_['S']['N'] = matchScore - 1;
	mat_['n']['S'] = matchScore - 1;
	mat_['S']['n'] = matchScore - 1;
	mat_['N']['s'] = matchScore - 1;
	mat_['s']['N'] = matchScore - 1;
	mat_['n']['s'] = matchScore - 1;
	mat_['s']['n'] = matchScore - 1;
	mat_['N']['W'] = matchScore - 1;
	mat_['W']['N'] = matchScore - 1;
	mat_['n']['W'] = matchScore - 1;
	mat_['W']['n'] = matchScore - 1;
	mat_['N']['w'] = matchScore - 1;
	mat_['w']['N'] = matchScore - 1;
	mat_['n']['w'] = matchScore - 1;
	mat_['w']['n'] = matchScore - 1;
	mat_['N']['R'] = matchScore - 1;
	mat_['R']['N'] = matchScore - 1;
	mat_['n']['R'] = matchScore - 1;
	mat_['R']['n'] = matchScore - 1;
	mat_['N']['r'] = matchScore - 1;
	mat_['r']['N'] = matchScore - 1;
	mat_['n']['r'] = matchScore - 1;
	mat_['r']['n'] = matchScore - 1;
	mat_['N']['B'] = matchScore - 1;
	mat_['B']['N'] = matchScore - 1;
	mat_['n']['B'] = matchScore - 1;
	mat_['B']['n'] = matchScore - 1;
	mat_['N']['b'] = matchScore - 1;
	mat_['b']['N'] = matchScore - 1;
	mat_['n']['b'] = matchScore - 1;
	mat_['b']['n'] = matchScore - 1;
	mat_['N']['M'] = matchScore - 1;
	mat_['M']['N'] = matchScore - 1;
	mat_['n']['M'] = matchScore - 1;
	mat_['M']['n'] = matchScore - 1;
	mat_['N']['m'] = matchScore - 1;
	mat_['m']['N'] = matchScore - 1;
	mat_['n']['m'] = matchScore - 1;
	mat_['m']['n'] = matchScore - 1;
}
void substituteMatrix::setWithDegenScoringNoNInRefCaseInsen(int32_t matchScore, int32_t mismatchScore){
	setWithSimpleCaseInsense(matchScore, mismatchScore);
	mat_['A']['D'] = matchScore;
	mat_['a']['D'] = matchScore;
	mat_['A']['d'] = matchScore;
	mat_['a']['d'] = matchScore;
	mat_['A']['V'] = matchScore;
	mat_['a']['V'] = matchScore;
	mat_['A']['v'] = matchScore;
	mat_['a']['v'] = matchScore;
	mat_['A']['N'] = matchScore;
	mat_['a']['N'] = matchScore;
	mat_['A']['n'] = matchScore;
	mat_['a']['n'] = matchScore;
	mat_['A']['H'] = matchScore;
	mat_['a']['H'] = matchScore;
	mat_['A']['h'] = matchScore;
	mat_['a']['h'] = matchScore;
	mat_['A']['W'] = matchScore;
	mat_['a']['W'] = matchScore;
	mat_['A']['w'] = matchScore;
	mat_['a']['w'] = matchScore;
	mat_['A']['R'] = matchScore;
	mat_['a']['R'] = matchScore;
	mat_['A']['r'] = matchScore;
	mat_['a']['r'] = matchScore;
	mat_['A']['M'] = matchScore;
	mat_['a']['M'] = matchScore;
	mat_['A']['m'] = matchScore;
	mat_['a']['m'] = matchScore;
	mat_['C']['V'] = matchScore;
	mat_['c']['V'] = matchScore;
	mat_['C']['v'] = matchScore;
	mat_['c']['v'] = matchScore;
	mat_['C']['N'] = matchScore;
	mat_['c']['N'] = matchScore;
	mat_['C']['n'] = matchScore;
	mat_['c']['n'] = matchScore;
	mat_['C']['Y'] = matchScore;
	mat_['c']['Y'] = matchScore;
	mat_['C']['y'] = matchScore;
	mat_['c']['y'] = matchScore;
	mat_['C']['H'] = matchScore;
	mat_['c']['H'] = matchScore;
	mat_['C']['h'] = matchScore;
	mat_['c']['h'] = matchScore;
	mat_['C']['S'] = matchScore;
	mat_['c']['S'] = matchScore;
	mat_['C']['s'] = matchScore;
	mat_['c']['s'] = matchScore;
	mat_['C']['B'] = matchScore;
	mat_['c']['B'] = matchScore;
	mat_['C']['b'] = matchScore;
	mat_['c']['b'] = matchScore;
	mat_['C']['M'] = matchScore;
	mat_['c']['M'] = matchScore;
	mat_['C']['m'] = matchScore;
	mat_['c']['m'] = matchScore;
	mat_['G']['D'] = matchScore;
	mat_['g']['D'] = matchScore;
	mat_['G']['d'] = matchScore;
	mat_['g']['d'] = matchScore;
	mat_['G']['V'] = matchScore;
	mat_['g']['V'] = matchScore;
	mat_['G']['v'] = matchScore;
	mat_['g']['v'] = matchScore;
	mat_['G']['K'] = matchScore;
	mat_['g']['K'] = matchScore;
	mat_['G']['k'] = matchScore;
	mat_['g']['k'] = matchScore;
	mat_['G']['N'] = matchScore;
	mat_['g']['N'] = matchScore;
	mat_['G']['n'] = matchScore;
	mat_['g']['n'] = matchScore;
	mat_['G']['S'] = matchScore;
	mat_['g']['S'] = matchScore;
	mat_['G']['s'] = matchScore;
	mat_['g']['s'] = matchScore;
	mat_['G']['R'] = matchScore;
	mat_['g']['R'] = matchScore;
	mat_['G']['r'] = matchScore;
	mat_['g']['r'] = matchScore;
	mat_['G']['B'] = matchScore;
	mat_['g']['B'] = matchScore;
	mat_['G']['b'] = matchScore;
	mat_['g']['b'] = matchScore;
	mat_['T']['D'] = matchScore;
	mat_['t']['D'] = matchScore;
	mat_['T']['d'] = matchScore;
	mat_['t']['d'] = matchScore;
	mat_['T']['K'] = matchScore;
	mat_['t']['K'] = matchScore;
	mat_['T']['k'] = matchScore;
	mat_['t']['k'] = matchScore;
	mat_['T']['N'] = matchScore;
	mat_['t']['N'] = matchScore;
	mat_['T']['n'] = matchScore;
	mat_['t']['n'] = matchScore;
	mat_['T']['Y'] = matchScore;
	mat_['t']['Y'] = matchScore;
	mat_['T']['y'] = matchScore;
	mat_['t']['y'] = matchScore;
	mat_['T']['H'] = matchScore;
	mat_['t']['H'] = matchScore;
	mat_['T']['h'] = matchScore;
	mat_['t']['h'] = matchScore;
	mat_['T']['W'] = matchScore;
	mat_['t']['W'] = matchScore;
	mat_['T']['w'] = matchScore;
	mat_['t']['w'] = matchScore;
	mat_['T']['B'] = matchScore;
	mat_['t']['B'] = matchScore;
	mat_['T']['b'] = matchScore;
	mat_['t']['b'] = matchScore;
}
void substituteMatrix::setWithDegenScoringNoNInRefCaseInsenLessN(int32_t matchScore, int32_t mismatchScore){
	setWithSimpleCaseInsense(matchScore, mismatchScore);
	mat_['A']['D'] = matchScore - 1;
	mat_['a']['D'] = matchScore - 1;
	mat_['A']['d'] = matchScore - 1;
	mat_['a']['d'] = matchScore - 1;
	mat_['A']['V'] = matchScore - 1;
	mat_['a']['V'] = matchScore - 1;
	mat_['A']['v'] = matchScore - 1;
	mat_['a']['v'] = matchScore - 1;
	mat_['A']['N'] = matchScore - 1;
	mat_['a']['N'] = matchScore - 1;
	mat_['A']['n'] = matchScore - 1;
	mat_['a']['n'] = matchScore - 1;
	mat_['A']['H'] = matchScore - 1;
	mat_['a']['H'] = matchScore - 1;
	mat_['A']['h'] = matchScore - 1;
	mat_['a']['h'] = matchScore - 1;
	mat_['A']['W'] = matchScore - 1;
	mat_['a']['W'] = matchScore - 1;
	mat_['A']['w'] = matchScore - 1;
	mat_['a']['w'] = matchScore - 1;
	mat_['A']['R'] = matchScore - 1;
	mat_['a']['R'] = matchScore - 1;
	mat_['A']['r'] = matchScore - 1;
	mat_['a']['r'] = matchScore - 1;
	mat_['A']['M'] = matchScore - 1;
	mat_['a']['M'] = matchScore - 1;
	mat_['A']['m'] = matchScore - 1;
	mat_['a']['m'] = matchScore - 1;
	mat_['C']['V'] = matchScore - 1;
	mat_['c']['V'] = matchScore - 1;
	mat_['C']['v'] = matchScore - 1;
	mat_['c']['v'] = matchScore - 1;
	mat_['C']['N'] = matchScore - 1;
	mat_['c']['N'] = matchScore - 1;
	mat_['C']['n'] = matchScore - 1;
	mat_['c']['n'] = matchScore - 1;
	mat_['C']['Y'] = matchScore - 1;
	mat_['c']['Y'] = matchScore - 1;
	mat_['C']['y'] = matchScore - 1;
	mat_['c']['y'] = matchScore - 1;
	mat_['C']['H'] = matchScore - 1;
	mat_['c']['H'] = matchScore - 1;
	mat_['C']['h'] = matchScore - 1;
	mat_['c']['h'] = matchScore - 1;
	mat_['C']['S'] = matchScore - 1;
	mat_['c']['S'] = matchScore - 1;
	mat_['C']['s'] = matchScore - 1;
	mat_['c']['s'] = matchScore - 1;
	mat_['C']['B'] = matchScore - 1;
	mat_['c']['B'] = matchScore - 1;
	mat_['C']['b'] = matchScore - 1;
	mat_['c']['b'] = matchScore - 1;
	mat_['C']['M'] = matchScore - 1;
	mat_['c']['M'] = matchScore - 1;
	mat_['C']['m'] = matchScore - 1;
	mat_['c']['m'] = matchScore - 1;
	mat_['G']['D'] = matchScore - 1;
	mat_['g']['D'] = matchScore - 1;
	mat_['G']['d'] = matchScore - 1;
	mat_['g']['d'] = matchScore - 1;
	mat_['G']['V'] = matchScore - 1;
	mat_['g']['V'] = matchScore - 1;
	mat_['G']['v'] = matchScore - 1;
	mat_['g']['v'] = matchScore - 1;
	mat_['G']['K'] = matchScore - 1;
	mat_['g']['K'] = matchScore - 1;
	mat_['G']['k'] = matchScore - 1;
	mat_['g']['k'] = matchScore - 1;
	mat_['G']['N'] = matchScore - 1;
	mat_['g']['N'] = matchScore - 1;
	mat_['G']['n'] = matchScore - 1;
	mat_['g']['n'] = matchScore - 1;
	mat_['G']['S'] = matchScore - 1;
	mat_['g']['S'] = matchScore - 1;
	mat_['G']['s'] = matchScore - 1;
	mat_['g']['s'] = matchScore - 1;
	mat_['G']['R'] = matchScore - 1;
	mat_['g']['R'] = matchScore - 1;
	mat_['G']['r'] = matchScore - 1;
	mat_['g']['r'] = matchScore - 1;
	mat_['G']['B'] = matchScore - 1;
	mat_['g']['B'] = matchScore - 1;
	mat_['G']['b'] = matchScore - 1;
	mat_['g']['b'] = matchScore - 1;
	mat_['T']['D'] = matchScore - 1;
	mat_['t']['D'] = matchScore - 1;
	mat_['T']['d'] = matchScore - 1;
	mat_['t']['d'] = matchScore - 1;
	mat_['T']['K'] = matchScore - 1;
	mat_['t']['K'] = matchScore - 1;
	mat_['T']['k'] = matchScore - 1;
	mat_['t']['k'] = matchScore - 1;
	mat_['T']['N'] = matchScore - 1;
	mat_['t']['N'] = matchScore - 1;
	mat_['T']['n'] = matchScore - 1;
	mat_['t']['n'] = matchScore - 1;
	mat_['T']['Y'] = matchScore - 1;
	mat_['t']['Y'] = matchScore - 1;
	mat_['T']['y'] = matchScore - 1;
	mat_['t']['y'] = matchScore - 1;
	mat_['T']['H'] = matchScore - 1;
	mat_['t']['H'] = matchScore - 1;
	mat_['T']['h'] = matchScore - 1;
	mat_['t']['h'] = matchScore - 1;
	mat_['T']['W'] = matchScore - 1;
	mat_['t']['W'] = matchScore - 1;
	mat_['T']['w'] = matchScore - 1;
	mat_['t']['w'] = matchScore - 1;
	mat_['T']['B'] = matchScore - 1;
	mat_['t']['B'] = matchScore - 1;
	mat_['T']['b'] = matchScore - 1;
	mat_['t']['b'] = matchScore - 1;
}
void substituteMatrix::setWithDegenScoringNoNInSeqCaseInsen(int32_t matchScore, int32_t mismatchScore){
	setWithSimpleCaseInsense(matchScore, mismatchScore);
	mat_['D']['A'] = matchScore;
	mat_['D']['a'] = matchScore;
	mat_['d']['A'] = matchScore;
	mat_['d']['a'] = matchScore;
	mat_['V']['A'] = matchScore;
	mat_['V']['a'] = matchScore;
	mat_['v']['A'] = matchScore;
	mat_['v']['a'] = matchScore;
	mat_['N']['A'] = matchScore;
	mat_['N']['a'] = matchScore;
	mat_['n']['A'] = matchScore;
	mat_['n']['a'] = matchScore;
	mat_['H']['A'] = matchScore;
	mat_['H']['a'] = matchScore;
	mat_['h']['A'] = matchScore;
	mat_['h']['a'] = matchScore;
	mat_['W']['A'] = matchScore;
	mat_['W']['a'] = matchScore;
	mat_['w']['A'] = matchScore;
	mat_['w']['a'] = matchScore;
	mat_['R']['A'] = matchScore;
	mat_['R']['a'] = matchScore;
	mat_['r']['A'] = matchScore;
	mat_['r']['a'] = matchScore;
	mat_['M']['A'] = matchScore;
	mat_['M']['a'] = matchScore;
	mat_['m']['A'] = matchScore;
	mat_['m']['a'] = matchScore;
	mat_['V']['C'] = matchScore;
	mat_['V']['c'] = matchScore;
	mat_['v']['C'] = matchScore;
	mat_['v']['c'] = matchScore;
	mat_['N']['C'] = matchScore;
	mat_['N']['c'] = matchScore;
	mat_['n']['C'] = matchScore;
	mat_['n']['c'] = matchScore;
	mat_['Y']['C'] = matchScore;
	mat_['Y']['c'] = matchScore;
	mat_['y']['C'] = matchScore;
	mat_['y']['c'] = matchScore;
	mat_['H']['C'] = matchScore;
	mat_['H']['c'] = matchScore;
	mat_['h']['C'] = matchScore;
	mat_['h']['c'] = matchScore;
	mat_['S']['C'] = matchScore;
	mat_['S']['c'] = matchScore;
	mat_['s']['C'] = matchScore;
	mat_['s']['c'] = matchScore;
	mat_['B']['C'] = matchScore;
	mat_['B']['c'] = matchScore;
	mat_['b']['C'] = matchScore;
	mat_['b']['c'] = matchScore;
	mat_['M']['C'] = matchScore;
	mat_['M']['c'] = matchScore;
	mat_['m']['C'] = matchScore;
	mat_['m']['c'] = matchScore;
	mat_['D']['G'] = matchScore;
	mat_['D']['g'] = matchScore;
	mat_['d']['G'] = matchScore;
	mat_['d']['g'] = matchScore;
	mat_['V']['G'] = matchScore;
	mat_['V']['g'] = matchScore;
	mat_['v']['G'] = matchScore;
	mat_['v']['g'] = matchScore;
	mat_['K']['G'] = matchScore;
	mat_['K']['g'] = matchScore;
	mat_['k']['G'] = matchScore;
	mat_['k']['g'] = matchScore;
	mat_['N']['G'] = matchScore;
	mat_['N']['g'] = matchScore;
	mat_['n']['G'] = matchScore;
	mat_['n']['g'] = matchScore;
	mat_['S']['G'] = matchScore;
	mat_['S']['g'] = matchScore;
	mat_['s']['G'] = matchScore;
	mat_['s']['g'] = matchScore;
	mat_['R']['G'] = matchScore;
	mat_['R']['g'] = matchScore;
	mat_['r']['G'] = matchScore;
	mat_['r']['g'] = matchScore;
	mat_['B']['G'] = matchScore;
	mat_['B']['g'] = matchScore;
	mat_['b']['G'] = matchScore;
	mat_['b']['g'] = matchScore;
	mat_['D']['T'] = matchScore;
	mat_['D']['t'] = matchScore;
	mat_['d']['T'] = matchScore;
	mat_['d']['t'] = matchScore;
	mat_['K']['T'] = matchScore;
	mat_['K']['t'] = matchScore;
	mat_['k']['T'] = matchScore;
	mat_['k']['t'] = matchScore;
	mat_['N']['T'] = matchScore;
	mat_['N']['t'] = matchScore;
	mat_['n']['T'] = matchScore;
	mat_['n']['t'] = matchScore;
	mat_['Y']['T'] = matchScore;
	mat_['Y']['t'] = matchScore;
	mat_['y']['T'] = matchScore;
	mat_['y']['t'] = matchScore;
	mat_['H']['T'] = matchScore;
	mat_['H']['t'] = matchScore;
	mat_['h']['T'] = matchScore;
	mat_['h']['t'] = matchScore;
	mat_['W']['T'] = matchScore;
	mat_['W']['t'] = matchScore;
	mat_['w']['T'] = matchScore;
	mat_['w']['t'] = matchScore;
	mat_['B']['T'] = matchScore;
	mat_['B']['t'] = matchScore;
	mat_['b']['T'] = matchScore;
	mat_['b']['t'] = matchScore;
}
void substituteMatrix::setWithDegenScoringNoNInSeqCaseInsenLessN(int32_t matchScore, int32_t mismatchScore){
	setWithSimpleCaseInsense(matchScore, mismatchScore);
	mat_['D']['A'] = matchScore - 1;
	mat_['D']['a'] = matchScore - 1;
	mat_['d']['A'] = matchScore - 1;
	mat_['d']['a'] = matchScore - 1;
	mat_['V']['A'] = matchScore - 1;
	mat_['V']['a'] = matchScore - 1;
	mat_['v']['A'] = matchScore - 1;
	mat_['v']['a'] = matchScore - 1;
	mat_['N']['A'] = matchScore - 1;
	mat_['N']['a'] = matchScore - 1;
	mat_['n']['A'] = matchScore - 1;
	mat_['n']['a'] = matchScore - 1;
	mat_['H']['A'] = matchScore - 1;
	mat_['H']['a'] = matchScore - 1;
	mat_['h']['A'] = matchScore - 1;
	mat_['h']['a'] = matchScore - 1;
	mat_['W']['A'] = matchScore - 1;
	mat_['W']['a'] = matchScore - 1;
	mat_['w']['A'] = matchScore - 1;
	mat_['w']['a'] = matchScore - 1;
	mat_['R']['A'] = matchScore - 1;
	mat_['R']['a'] = matchScore - 1;
	mat_['r']['A'] = matchScore - 1;
	mat_['r']['a'] = matchScore - 1;
	mat_['M']['A'] = matchScore - 1;
	mat_['M']['a'] = matchScore - 1;
	mat_['m']['A'] = matchScore - 1;
	mat_['m']['a'] = matchScore - 1;
	mat_['V']['C'] = matchScore - 1;
	mat_['V']['c'] = matchScore - 1;
	mat_['v']['C'] = matchScore - 1;
	mat_['v']['c'] = matchScore - 1;
	mat_['N']['C'] = matchScore - 1;
	mat_['N']['c'] = matchScore - 1;
	mat_['n']['C'] = matchScore - 1;
	mat_['n']['c'] = matchScore - 1;
	mat_['Y']['C'] = matchScore - 1;
	mat_['Y']['c'] = matchScore - 1;
	mat_['y']['C'] = matchScore - 1;
	mat_['y']['c'] = matchScore - 1;
	mat_['H']['C'] = matchScore - 1;
	mat_['H']['c'] = matchScore - 1;
	mat_['h']['C'] = matchScore - 1;
	mat_['h']['c'] = matchScore - 1;
	mat_['S']['C'] = matchScore - 1;
	mat_['S']['c'] = matchScore - 1;
	mat_['s']['C'] = matchScore - 1;
	mat_['s']['c'] = matchScore - 1;
	mat_['B']['C'] = matchScore - 1;
	mat_['B']['c'] = matchScore - 1;
	mat_['b']['C'] = matchScore - 1;
	mat_['b']['c'] = matchScore - 1;
	mat_['M']['C'] = matchScore - 1;
	mat_['M']['c'] = matchScore - 1;
	mat_['m']['C'] = matchScore - 1;
	mat_['m']['c'] = matchScore - 1;
	mat_['D']['G'] = matchScore - 1;
	mat_['D']['g'] = matchScore - 1;
	mat_['d']['G'] = matchScore - 1;
	mat_['d']['g'] = matchScore - 1;
	mat_['V']['G'] = matchScore - 1;
	mat_['V']['g'] = matchScore - 1;
	mat_['v']['G'] = matchScore - 1;
	mat_['v']['g'] = matchScore - 1;
	mat_['K']['G'] = matchScore - 1;
	mat_['K']['g'] = matchScore - 1;
	mat_['k']['G'] = matchScore - 1;
	mat_['k']['g'] = matchScore - 1;
	mat_['N']['G'] = matchScore - 1;
	mat_['N']['g'] = matchScore - 1;
	mat_['n']['G'] = matchScore - 1;
	mat_['n']['g'] = matchScore - 1;
	mat_['S']['G'] = matchScore - 1;
	mat_['S']['g'] = matchScore - 1;
	mat_['s']['G'] = matchScore - 1;
	mat_['s']['g'] = matchScore - 1;
	mat_['R']['G'] = matchScore - 1;
	mat_['R']['g'] = matchScore - 1;
	mat_['r']['G'] = matchScore - 1;
	mat_['r']['g'] = matchScore - 1;
	mat_['B']['G'] = matchScore - 1;
	mat_['B']['g'] = matchScore - 1;
	mat_['b']['G'] = matchScore - 1;
	mat_['b']['g'] = matchScore - 1;
	mat_['D']['T'] = matchScore - 1;
	mat_['D']['t'] = matchScore - 1;
	mat_['d']['T'] = matchScore - 1;
	mat_['d']['t'] = matchScore - 1;
	mat_['K']['T'] = matchScore - 1;
	mat_['K']['t'] = matchScore - 1;
	mat_['k']['T'] = matchScore - 1;
	mat_['k']['t'] = matchScore - 1;
	mat_['N']['T'] = matchScore - 1;
	mat_['N']['t'] = matchScore - 1;
	mat_['n']['T'] = matchScore - 1;
	mat_['n']['t'] = matchScore - 1;
	mat_['Y']['T'] = matchScore - 1;
	mat_['Y']['t'] = matchScore - 1;
	mat_['y']['T'] = matchScore - 1;
	mat_['y']['t'] = matchScore - 1;
	mat_['H']['T'] = matchScore - 1;
	mat_['H']['t'] = matchScore - 1;
	mat_['h']['T'] = matchScore - 1;
	mat_['h']['t'] = matchScore - 1;
	mat_['W']['T'] = matchScore - 1;
	mat_['W']['t'] = matchScore - 1;
	mat_['w']['T'] = matchScore - 1;
	mat_['w']['t'] = matchScore - 1;
	mat_['B']['T'] = matchScore - 1;
	mat_['B']['t'] = matchScore - 1;
	mat_['b']['T'] = matchScore - 1;
	mat_['b']['t'] = matchScore - 1;
}
void substituteMatrix::setWithDegenScoringCaseSense(int32_t matchScore, int32_t mismatchScore){
	setWithSimple(matchScore, mismatchScore);
	mat_['A']['D'] = matchScore;
	mat_['D']['A'] = matchScore;
	mat_['A']['V'] = matchScore;
	mat_['V']['A'] = matchScore;
	mat_['A']['N'] = matchScore;
	mat_['N']['A'] = matchScore;
	mat_['A']['H'] = matchScore;
	mat_['H']['A'] = matchScore;
	mat_['A']['W'] = matchScore;
	mat_['W']['A'] = matchScore;
	mat_['A']['R'] = matchScore;
	mat_['R']['A'] = matchScore;
	mat_['A']['M'] = matchScore;
	mat_['M']['A'] = matchScore;
	mat_['C']['V'] = matchScore;
	mat_['V']['C'] = matchScore;
	mat_['C']['N'] = matchScore;
	mat_['N']['C'] = matchScore;
	mat_['C']['Y'] = matchScore;
	mat_['Y']['C'] = matchScore;
	mat_['C']['H'] = matchScore;
	mat_['H']['C'] = matchScore;
	mat_['C']['S'] = matchScore;
	mat_['S']['C'] = matchScore;
	mat_['C']['B'] = matchScore;
	mat_['B']['C'] = matchScore;
	mat_['C']['M'] = matchScore;
	mat_['M']['C'] = matchScore;
	mat_['G']['D'] = matchScore;
	mat_['D']['G'] = matchScore;
	mat_['G']['V'] = matchScore;
	mat_['V']['G'] = matchScore;
	mat_['G']['K'] = matchScore;
	mat_['K']['G'] = matchScore;
	mat_['G']['N'] = matchScore;
	mat_['N']['G'] = matchScore;
	mat_['G']['S'] = matchScore;
	mat_['S']['G'] = matchScore;
	mat_['G']['R'] = matchScore;
	mat_['R']['G'] = matchScore;
	mat_['G']['B'] = matchScore;
	mat_['B']['G'] = matchScore;
	mat_['T']['D'] = matchScore;
	mat_['D']['T'] = matchScore;
	mat_['T']['K'] = matchScore;
	mat_['K']['T'] = matchScore;
	mat_['T']['N'] = matchScore;
	mat_['N']['T'] = matchScore;
	mat_['T']['Y'] = matchScore;
	mat_['Y']['T'] = matchScore;
	mat_['T']['H'] = matchScore;
	mat_['H']['T'] = matchScore;
	mat_['T']['W'] = matchScore;
	mat_['W']['T'] = matchScore;
	mat_['T']['B'] = matchScore;
	mat_['B']['T'] = matchScore;
	mat_['N']['D'] = matchScore;
	mat_['D']['N'] = matchScore;
	mat_['N']['V'] = matchScore;
	mat_['V']['N'] = matchScore;
	mat_['N']['K'] = matchScore;
	mat_['K']['N'] = matchScore;
	mat_['N']['Y'] = matchScore;
	mat_['Y']['N'] = matchScore;
	mat_['N']['H'] = matchScore;
	mat_['H']['N'] = matchScore;
	mat_['N']['S'] = matchScore;
	mat_['S']['N'] = matchScore;
	mat_['N']['W'] = matchScore;
	mat_['W']['N'] = matchScore;
	mat_['N']['R'] = matchScore;
	mat_['R']['N'] = matchScore;
	mat_['N']['B'] = matchScore;
	mat_['B']['N'] = matchScore;
	mat_['N']['M'] = matchScore;
	mat_['M']['N'] = matchScore;
}
void substituteMatrix::setWithDegenScoringLessNCaseSense(int32_t matchScore, int32_t mismatchScore){
	setWithSimple(matchScore, mismatchScore);
	mat_['A']['D'] = matchScore - 1;
	mat_['D']['A'] = matchScore - 1;
	mat_['A']['V'] = matchScore - 1;
	mat_['V']['A'] = matchScore - 1;
	mat_['A']['N'] = matchScore - 1;
	mat_['N']['A'] = matchScore - 1;
	mat_['A']['H'] = matchScore - 1;
	mat_['H']['A'] = matchScore - 1;
	mat_['A']['W'] = matchScore - 1;
	mat_['W']['A'] = matchScore - 1;
	mat_['A']['R'] = matchScore - 1;
	mat_['R']['A'] = matchScore - 1;
	mat_['A']['M'] = matchScore - 1;
	mat_['M']['A'] = matchScore - 1;
	mat_['C']['V'] = matchScore - 1;
	mat_['V']['C'] = matchScore - 1;
	mat_['C']['N'] = matchScore - 1;
	mat_['N']['C'] = matchScore - 1;
	mat_['C']['Y'] = matchScore - 1;
	mat_['Y']['C'] = matchScore - 1;
	mat_['C']['H'] = matchScore - 1;
	mat_['H']['C'] = matchScore - 1;
	mat_['C']['S'] = matchScore - 1;
	mat_['S']['C'] = matchScore - 1;
	mat_['C']['B'] = matchScore - 1;
	mat_['B']['C'] = matchScore - 1;
	mat_['C']['M'] = matchScore - 1;
	mat_['M']['C'] = matchScore - 1;
	mat_['G']['D'] = matchScore - 1;
	mat_['D']['G'] = matchScore - 1;
	mat_['G']['V'] = matchScore - 1;
	mat_['V']['G'] = matchScore - 1;
	mat_['G']['K'] = matchScore - 1;
	mat_['K']['G'] = matchScore - 1;
	mat_['G']['N'] = matchScore - 1;
	mat_['N']['G'] = matchScore - 1;
	mat_['G']['S'] = matchScore - 1;
	mat_['S']['G'] = matchScore - 1;
	mat_['G']['R'] = matchScore - 1;
	mat_['R']['G'] = matchScore - 1;
	mat_['G']['B'] = matchScore - 1;
	mat_['B']['G'] = matchScore - 1;
	mat_['T']['D'] = matchScore - 1;
	mat_['D']['T'] = matchScore - 1;
	mat_['T']['K'] = matchScore - 1;
	mat_['K']['T'] = matchScore - 1;
	mat_['T']['N'] = matchScore - 1;
	mat_['N']['T'] = matchScore - 1;
	mat_['T']['Y'] = matchScore - 1;
	mat_['Y']['T'] = matchScore - 1;
	mat_['T']['H'] = matchScore - 1;
	mat_['H']['T'] = matchScore - 1;
	mat_['T']['W'] = matchScore - 1;
	mat_['W']['T'] = matchScore - 1;
	mat_['T']['B'] = matchScore - 1;
	mat_['B']['T'] = matchScore - 1;
	mat_['N']['D'] = matchScore - 1;
	mat_['D']['N'] = matchScore - 1;
	mat_['N']['V'] = matchScore - 1;
	mat_['V']['N'] = matchScore - 1;
	mat_['N']['K'] = matchScore - 1;
	mat_['K']['N'] = matchScore - 1;
	mat_['N']['Y'] = matchScore - 1;
	mat_['Y']['N'] = matchScore - 1;
	mat_['N']['H'] = matchScore - 1;
	mat_['H']['N'] = matchScore - 1;
	mat_['N']['S'] = matchScore - 1;
	mat_['S']['N'] = matchScore - 1;
	mat_['N']['W'] = matchScore - 1;
	mat_['W']['N'] = matchScore - 1;
	mat_['N']['R'] = matchScore - 1;
	mat_['R']['N'] = matchScore - 1;
	mat_['N']['B'] = matchScore - 1;
	mat_['B']['N'] = matchScore - 1;
	mat_['N']['M'] = matchScore - 1;
	mat_['M']['N'] = matchScore - 1;
}
void substituteMatrix::setWithDegenScoringNoNInRefCaseSense(int32_t matchScore, int32_t mismatchScore){
	setWithSimple(matchScore, mismatchScore);
	mat_['A']['D'] = matchScore;
	mat_['A']['V'] = matchScore;
	mat_['A']['N'] = matchScore;
	mat_['A']['H'] = matchScore;
	mat_['A']['W'] = matchScore;
	mat_['A']['R'] = matchScore;
	mat_['A']['M'] = matchScore;
	mat_['C']['V'] = matchScore;
	mat_['C']['N'] = matchScore;
	mat_['C']['Y'] = matchScore;
	mat_['C']['H'] = matchScore;
	mat_['C']['S'] = matchScore;
	mat_['C']['B'] = matchScore;
	mat_['C']['M'] = matchScore;
	mat_['G']['D'] = matchScore;
	mat_['G']['V'] = matchScore;
	mat_['G']['K'] = matchScore;
	mat_['G']['N'] = matchScore;
	mat_['G']['S'] = matchScore;
	mat_['G']['R'] = matchScore;
	mat_['G']['B'] = matchScore;
	mat_['T']['D'] = matchScore;
	mat_['T']['K'] = matchScore;
	mat_['T']['N'] = matchScore;
	mat_['T']['Y'] = matchScore;
	mat_['T']['H'] = matchScore;
	mat_['T']['W'] = matchScore;
	mat_['T']['B'] = matchScore;
}
void substituteMatrix::setWithDegenScoringNoNInRefCaseSenseLessN(int32_t matchScore, int32_t mismatchScore){
	setWithSimple(matchScore, mismatchScore);
	mat_['A']['D'] = matchScore - 1;
	mat_['A']['V'] = matchScore - 1;
	mat_['A']['N'] = matchScore - 1;
	mat_['A']['H'] = matchScore - 1;
	mat_['A']['W'] = matchScore - 1;
	mat_['A']['R'] = matchScore - 1;
	mat_['A']['M'] = matchScore - 1;
	mat_['C']['V'] = matchScore - 1;
	mat_['C']['N'] = matchScore - 1;
	mat_['C']['Y'] = matchScore - 1;
	mat_['C']['H'] = matchScore - 1;
	mat_['C']['S'] = matchScore - 1;
	mat_['C']['B'] = matchScore - 1;
	mat_['C']['M'] = matchScore - 1;
	mat_['G']['D'] = matchScore - 1;
	mat_['G']['V'] = matchScore - 1;
	mat_['G']['K'] = matchScore - 1;
	mat_['G']['N'] = matchScore - 1;
	mat_['G']['S'] = matchScore - 1;
	mat_['G']['R'] = matchScore - 1;
	mat_['G']['B'] = matchScore - 1;
	mat_['T']['D'] = matchScore - 1;
	mat_['T']['K'] = matchScore - 1;
	mat_['T']['N'] = matchScore - 1;
	mat_['T']['Y'] = matchScore - 1;
	mat_['T']['H'] = matchScore - 1;
	mat_['T']['W'] = matchScore - 1;
	mat_['T']['B'] = matchScore - 1;
}
void substituteMatrix::setWithDegenScoringNoNInSeqCaseSense(int32_t matchScore, int32_t mismatchScore){
	setWithSimple(matchScore, mismatchScore);
	mat_['D']['A'] = matchScore;
	mat_['V']['A'] = matchScore;
	mat_['N']['A'] = matchScore;
	mat_['H']['A'] = matchScore;
	mat_['W']['A'] = matchScore;
	mat_['R']['A'] = matchScore;
	mat_['M']['A'] = matchScore;
	mat_['V']['C'] = matchScore;
	mat_['N']['C'] = matchScore;
	mat_['Y']['C'] = matchScore;
	mat_['H']['C'] = matchScore;
	mat_['S']['C'] = matchScore;
	mat_['B']['C'] = matchScore;
	mat_['M']['C'] = matchScore;
	mat_['D']['G'] = matchScore;
	mat_['V']['G'] = matchScore;
	mat_['K']['G'] = matchScore;
	mat_['N']['G'] = matchScore;
	mat_['S']['G'] = matchScore;
	mat_['R']['G'] = matchScore;
	mat_['B']['G'] = matchScore;
	mat_['D']['T'] = matchScore;
	mat_['K']['T'] = matchScore;
	mat_['N']['T'] = matchScore;
	mat_['Y']['T'] = matchScore;
	mat_['H']['T'] = matchScore;
	mat_['W']['T'] = matchScore;
	mat_['B']['T'] = matchScore;
}
void substituteMatrix::setWithDegenScoringNoNInSeqCaseSenseLessN(int32_t matchScore, int32_t mismatchScore){
	setWithSimple(matchScore, mismatchScore);
	mat_['D']['A'] = matchScore - 1;
	mat_['V']['A'] = matchScore - 1;
	mat_['N']['A'] = matchScore - 1;
	mat_['H']['A'] = matchScore - 1;
	mat_['W']['A'] = matchScore - 1;
	mat_['R']['A'] = matchScore - 1;
	mat_['M']['A'] = matchScore - 1;
	mat_['V']['C'] = matchScore - 1;
	mat_['N']['C'] = matchScore - 1;
	mat_['Y']['C'] = matchScore - 1;
	mat_['H']['C'] = matchScore - 1;
	mat_['S']['C'] = matchScore - 1;
	mat_['B']['C'] = matchScore - 1;
	mat_['M']['C'] = matchScore - 1;
	mat_['D']['G'] = matchScore - 1;
	mat_['V']['G'] = matchScore - 1;
	mat_['K']['G'] = matchScore - 1;
	mat_['N']['G'] = matchScore - 1;
	mat_['S']['G'] = matchScore - 1;
	mat_['R']['G'] = matchScore - 1;
	mat_['B']['G'] = matchScore - 1;
	mat_['D']['T'] = matchScore - 1;
	mat_['K']['T'] = matchScore - 1;
	mat_['N']['T'] = matchScore - 1;
	mat_['Y']['T'] = matchScore - 1;
	mat_['H']['T'] = matchScore - 1;
	mat_['W']['T'] = matchScore - 1;
	mat_['B']['T'] = matchScore - 1;
}

void substituteMatrix::setWithFilename(const std::string & filename){

  auto matchMatrixScoresMap = seqUtil::readScoringMatrix(filename);
  setWithUnoMap(matchMatrixScoresMap);
}
void substituteMatrix::printScores(const std::vector<char> & alphabet,
		std::ostream & out)const{
	VecStr head = {"let"};
	VecStr alphStr (alphabet.size());
	std::transform(alphabet.begin(), alphabet.end(), alphStr.begin(),
			[&](const char & c){return to_string(c);});
	addOtherVec(head, alphStr);
	std::vector<VecStr> outContent;
	for(const auto & let : alphabet){
		VecStr currentRow = {to_string(let)};
		for(const auto & secondLet : alphabet){
			currentRow.emplace_back(to_string(mat_[let][secondLet]));
		}
		outContent.emplace_back(currentRow);
	}
	printTableOrganized(outContent, head, out);
}

void substituteMatrix::printScores(std::ostream & out)const{
	VecStr head = {"let"};
	auto alphabet = determineLetters();
	VecStr alphStr (alphabet.size());
	std::transform(alphabet.begin(), alphabet.end(), alphStr.begin(), [&](const char & c){return to_string(c);});
	addOtherVec(head, alphStr);
	std::vector<VecStr> outContent;
	for(const auto & let : alphabet){
		VecStr currentRow = {to_string(let)};
		for(const auto & secondLet : alphabet){
			currentRow.emplace_back(to_string(mat_[let][secondLet]));
		}
		outContent.emplace_back(currentRow);
	}
	printTableOrganized(outContent, head, out);
}

substituteMatrix substituteMatrix::createDegenScoreMatrix(int32_t matchScore, int32_t mismatchScore){
	substituteMatrix degen;
	degen.setWithDegenScoringCaseSense(matchScore, mismatchScore);
	return degen;
}
substituteMatrix substituteMatrix::createDegenScoreMatrixCaseInsensitive(int32_t matchScore, int32_t mismatchScore){
	substituteMatrix degen;
	degen.setWithDegenScoringCaseInsen(matchScore, mismatchScore);
	return degen;
}
substituteMatrix substituteMatrix::createDegenScoreMatrixLessN(int32_t matchScore, int32_t mismatchScore){
	substituteMatrix degen;
	degen.setWithDegenScoringLessNCaseSense(matchScore, mismatchScore);
	return degen;
}

substituteMatrix substituteMatrix::createDegenScoreMatrixNoNInRef(int32_t matchScore, int32_t mismatchScore){
	substituteMatrix degen;
	degen.setWithDegenScoringNoNInRefCaseSense(matchScore, mismatchScore);
	return degen;
}

substituteMatrix substituteMatrix::createScoreMatrix(int32_t matchScore, int32_t mismatchScore,
		bool degenerativeScoring, bool degenLessN, bool caseInsensitive){
  substituteMatrix scoring;
  if(degenerativeScoring){
  	if(caseInsensitive){
  		if(degenLessN){
  			scoring.setWithDegenScoringLessNCaseInsen(matchScore, mismatchScore);
  		}else{
  			scoring.setWithDegenScoringCaseInsen(matchScore, mismatchScore);
  		}
  	}else{
  		if(degenLessN){
  			scoring.setWithDegenScoringLessNCaseSense(matchScore, mismatchScore);
  		}else{
  			scoring.setWithDegenScoringCaseSense(matchScore, mismatchScore);
  		}
  	}
  }else{
  	if(caseInsensitive){
  		scoring.setWithSimpleCaseInsense(matchScore, mismatchScore);
  	}else{
  		scoring.setWithSimple(matchScore, mismatchScore);
  	}
  }
  return scoring;
}

} /* namespace bib */
